import type { Question } from "./types.ts";

function deck(
  game: Question["game"],
  groups: Record<string, string[]>,
): Question[] {
  return Object.entries(groups).flatMap(([category, prompts]) =>
    prompts.map((prompt, index) => ({
      id: `${game}-${category.toLowerCase()}-${index + 1}`,
      game,
      category,
      prompt,
    })),
  );
}

export const thisOrThatQuestions: Question[] = Object.entries({
  Travel: [
    "Mountains|Beach",
    "City break|Countryside escape",
    "Road trip|Train journey",
    "One long holiday|Several short trips",
    "Museum afternoon|Local market morning",
    "Snowy cabin|Seaside cottage",
    "Travel with a plan|Follow your curiosity",
    "Return to a favorite place|Go somewhere new",
    "Sunrise hike|Midnight walk",
    "Camping|Boutique hotel",
  ],
  Lifestyle: [
    "Early mornings|Late nights",
    "A full calendar|An open weekend",
    "Cook together|Order takeaway",
    "Live abroad|Stay close to home",
    "Minimalist home|Home full of keepsakes",
    "A busy city|A quiet village",
    "Phone call|Voice message",
    "Finish one book|Read several at once",
    "A tidy desk|Creative chaos",
    "Save for a big experience|Enjoy small treats often",
  ],
  Food: [
    "Sweet breakfast|Savory breakfast",
    "Pizza night|Sushi night",
    "Coffee|Tea",
    "Try a new restaurant|Return to a favorite",
    "Chocolate dessert|Fruit dessert",
    "Spicy food|Mild food",
    "Picnic|Candlelit dinner",
    "Pasta|Tacos",
    "Bake something|Cook something",
    "Share one dessert|Choose your own",
  ],
  Us: [
    "A thoughtful note|A surprise outing",
    "Stay in|Go out",
    "Dance together|Sing together",
    "A long hug|Holding hands",
    "Plan a date|Be surprised",
    "Matching hobbies|Different interests",
    "Take photos|Stay in the moment",
    "Big celebration|Quiet celebration",
    "Breakfast date|Evening date",
    "Revisit our first date|Invent a new tradition",
  ],
  Future: [
    "A garden|A rooftop terrace",
    "Learn a language|Learn an instrument",
    "Build something|Grow something",
    "A year of travel|A year creating a home",
    "Adopt a dog|Adopt a cat",
    "A home library|A home cinema",
    "Work from anywhere|Have a dedicated studio",
    "Learn to sail|Learn to ski",
    "Host friends often|Meet friends out",
    "A tiny house|An old house to restore",
  ],
  Funny: [
    "Talk to animals|Speak every language",
    "Teleport|Fly",
    "Always find lost things|Always pick the right queue",
    "A personal chef|A personal driver",
    "Win a quiz show|Win a dance contest",
    "Only whisper|Only sing",
    "Be in a musical|Be in a mystery",
    "Swap playlists|Swap wardrobes",
    "Know every movie ending|Never remember spoilers",
    "A week without mirrors|A week without clocks",
  ],
}).flatMap(([category, items]) =>
  items.map((pair, i) => {
    const [optionA, optionB] = pair.split("|");
    return {
      id: `this-or-that-${category.toLowerCase()}-${i + 1}`,
      game: "this-or-that" as const,
      category,
      prompt: "This or that?",
      optionA,
      optionB,
    };
  }),
);

export const knowMeQuestions = deck("do-you-know-me", {
  Easy: [
    "What is my comfort food?",
    "What would my ideal Sunday look like?",
    "Which season do I enjoy most?",
    "What drink do I usually order?",
    "Which film could I watch again and again?",
    "What is my favorite way to exercise?",
    "Am I most energetic in the morning or evening?",
    "What is my favorite holiday destination so far?",
    "Which snack would I pick on a road trip?",
    "What kind of weather makes me happiest?",
    "What is my favorite room at home?",
    "Which music do I put on to relax?",
    "What breakfast would I choose today?",
  ],
  Personal: [
    "What usually cheers me up after a difficult day?",
    "What achievement am I proud of?",
    "What is a skill I want to improve?",
    "What makes me feel appreciated?",
    "What helps me feel calm?",
    "What quality do I value most in a friend?",
    "What do I find hardest to ask for?",
    "What small thing makes me laugh?",
    "What is a habit I am trying to build?",
    "When do I feel most confident?",
    "What is something I tend to overthink?",
    "What kind of compliment means most to me?",
    "How do I prefer to spend time alone?",
  ],
  Future: [
    "Where would I love to live for a year?",
    "Which place is still on my travel list?",
    "What would I like to learn next?",
    "What would my dream home include?",
    "Which adventure would I choose for us?",
    "What would I do with a free month?",
    "What personal goal matters to me this year?",
    "What would I love to create?",
    "What tradition would I like us to start?",
    "Which job would I try for a day?",
    "What would I want more time for?",
    "What do I picture on an ideal birthday?",
  ],
  Funny: [
    "What would I spend a surprise €1,000 on first?",
    "What is my most useless talent?",
    "Which reality show would I last longest on?",
    "What animal best matches my personality?",
    "What would my karaoke song be?",
    "What would I name a boat?",
    "Which fictional world would I visit?",
    "What household task do I avoid most?",
    "What would I accidentally become famous for?",
    "What ridiculous invention would I buy?",
    "What would I pack first for a desert island?",
    "Which food could I eat for a whole week?",
  ],
});

export const deepTalkQuestions = deck("deep-talk", {
  Us: [
    "What is something you hope we never stop doing together?",
    "When do you feel most understood by me?",
    "Which ordinary moment with us would you keep?",
    "What has surprised you about our relationship?",
    "What does quality time mean to you lately?",
    "What is one way we make a good team?",
    "What would you like us to celebrate more often?",
    "Which small ritual feels like ours?",
    "What have we taught each other?",
    "What would make our next month together special?",
  ],
  Future: [
    "What would you like our life to feel like in five years?",
    "What matters more to you now than it did five years ago?",
    "What kind of home do you want to build emotionally?",
    "Which adventure should we stop postponing?",
    "What would a slower life look like for us?",
    "What do you want to make room for next year?",
    "Which future decision are you curious about?",
    "What would you like to learn together?",
    "What should remain the same as our lives change?",
    "What would you do if you had one completely free year?",
  ],
  Dreams: [
    "What dream have you kept mostly to yourself?",
    "What did you want to become before you knew what jobs paid?",
    "What would you create if nobody judged it?",
    "Which place lives in your imagination?",
    "What would your perfect ordinary day include?",
    "What would you attempt with a little more courage?",
    "What is a dream you have outgrown?",
    "Who inspires you to imagine more for yourself?",
    "What is a small dream we could make happen soon?",
    "What does success look like without an audience?",
  ],
  Childhood: [
    "Which childhood place can you still picture clearly?",
    "What made you feel safe as a child?",
    "What game could you play for hours?",
    "Which family saying has stayed with you?",
    "What did you love doing after school?",
    "Who noticed something special in you early on?",
    "What did your childhood bedroom look like?",
    "What food brings back a childhood memory?",
    "What did you misunderstand about adults?",
    "What would younger you be delighted by now?",
  ],
  Memories: [
    "Which day would you like to relive for an hour?",
    "What is a smell that takes you somewhere else?",
    "Which trip changed your perspective?",
    "What is a kindness you still remember?",
    "Which photo means more than it looks like?",
    "What is a favorite memory of laughing together?",
    "What ordinary day became unexpectedly important?",
    "Which song belongs to a particular time in your life?",
    "What is a moment you wish you had photographed?",
    "What is one memory you would like to tell me in more detail?",
  ],
  Funny: [
    "What would our extremely low-budget TV show be called?",
    "Which harmless rule would you invent for the world?",
    "What would we be terrible at as a team?",
    "What is the strangest thing you believed confidently?",
    "What would your autobiography title be this week?",
    "Which fictional character would be a terrible housemate?",
    "What is a tiny inconvenience you take too seriously?",
    "If our pet could review us, what would it say?",
    "What would you put in a museum of your life?",
    "What is a very specific talent you wish existed?",
  ],
  Vulnerable: [
    "What helps you feel comfortable being honest?",
    "What is something you are learning to accept about yourself?",
    "How can I support you when you feel overwhelmed?",
    "What does a sincere apology look like to you?",
    "When do you need listening rather than advice?",
    "What expectation would you like to let go of?",
    "What is something you find easier to write than say?",
    "What boundary helps you feel more present?",
    "What would you like to give yourself permission to do?",
    "What does feeling emotionally safe mean to you?",
  ],
  Random: [
    "What have you changed your mind about in recent years?",
    "What do you wish people asked you about more?",
    "Which small luxury improves your life most?",
    "What skill do you admire in other people?",
    "What is worth doing slowly?",
    "What kind of beauty do you notice first?",
    "What makes a place feel like home?",
    "What has been taking up your thoughts lately?",
    "What would you like to understand better?",
    "What are you grateful you no longer worry about?",
  ],
});

export const drawingWords = deck("drawing-word", {
  Objects: [
    "Umbrella",
    "Bicycle",
    "Camera",
    "Candle",
    "Backpack",
    "Clock",
    "Key",
    "Glasses",
    "Headphones",
    "Scissors",
    "Ladder",
    "Balloon",
    "Guitar",
    "Teapot",
    "Suitcase",
    "Toothbrush",
    "Telescope",
    "Book",
    "Lamp",
    "Kite",
  ],
  Animals: [
    "Elephant",
    "Penguin",
    "Giraffe",
    "Turtle",
    "Butterfly",
    "Octopus",
    "Rabbit",
    "Flamingo",
    "Hedgehog",
    "Dolphin",
    "Owl",
    "Snail",
    "Crab",
    "Frog",
    "Jellyfish",
    "Cat",
    "Dog",
    "Bee",
    "Shark",
    "Peacock",
  ],
  Food: [
    "Pizza",
    "Ice cream",
    "Watermelon",
    "Croissant",
    "Pancakes",
    "Popcorn",
    "Pineapple",
    "Taco",
    "Cupcake",
    "Banana",
    "Sushi",
    "Spaghetti",
    "Donut",
    "Carrot",
    "Strawberry",
    "Cheese",
    "Pretzel",
    "Avocado",
    "Sandwich",
    "Pear",
  ],
  Places: [
    "Lighthouse",
    "Castle",
    "Beach",
    "Volcano",
    "Bridge",
    "Treehouse",
    "Cinema",
    "Library",
    "Airport",
    "Farm",
    "Mountain",
    "Island",
    "Campsite",
    "Bakery",
    "Playground",
    "Train station",
    "Desert",
    "Waterfall",
    "Igloo",
    "Garden",
  ],
  Random: [
    "Rainbow",
    "Snowman",
    "Rocket",
    "Robot",
    "Mermaid",
    "Pirate",
    "Astronaut",
    "Treasure chest",
    "Hot air balloon",
    "Shooting star",
    "Campfire",
    "Snowflake",
    "Planet",
    "Ghost",
    "Crown",
    "Magic wand",
    "Love letter",
    "Roller coaster",
    "Dinosaur",
    "Compass",
  ],
});

export const dailyQuestions = deck("daily-us", {
  Connection: [
    "What is one thing you look forward to doing together?",
    "What made you think of me today?",
    "What would make tonight feel special?",
    "What is one thing you appreciated about us this week?",
    "What should our next small adventure be?",
    "What would you like to tell me more about?",
    "What is one thing we do well together?",
    "What would you like us to make time for?",
    "What is your favorite way to say hello after a long day?",
    "What shared moment would you repeat?",
    "What made you smile about us recently?",
    "What is one thing you would like to ask me?",
    "Which song would you send me today?",
    "What would you put in a care package for me?",
    "What is a little tradition you would like to keep?",
    "What would our ideal lunch break together look like?",
    "What is something you want to thank me for?",
    "What would you like to discover about each other?",
    "What is one way we can make tomorrow easier?",
    "What feels especially good about being a team?",
  ],
  Today: [
    "What was the best part of your day?",
    "What surprised you today?",
    "What gave you energy today?",
    "What would have made today easier?",
    "What are you proud of doing today?",
    "What did you notice on your way somewhere?",
    "What are you ready to leave behind tonight?",
    "What is one thing you learned today?",
    "What small kindness did you see?",
    "What would you like to remember about today?",
    "What are you looking forward to tomorrow?",
    "What helped you pause today?",
    "What would you like more of this week?",
    "What did you make time for yourself today?",
    "What is on your mind right now?",
    "What felt easier than you expected today?",
    "What was something beautiful you saw?",
    "What would the title of today be?",
    "What are you glad you said yes to?",
    "What did you enjoy eating today?",
  ],
  Appreciation: [
    "What is a quality you appreciate in yourself?",
    "Who made your week better?",
    "What part of home are you grateful for?",
    "What recent conversation stayed with you?",
    "What is something you used to wish for that you have now?",
    "What simple comfort do you love?",
    "What skill are you glad you learned?",
    "What is something your body helped you do today?",
    "Which friend are you glad is in your life?",
    "What is something you like about this season?",
    "What do you appreciate about our differences?",
    "What family memory makes you smile?",
    "What is a place you are glad exists?",
    "What do you enjoy about your daily routine?",
    "What is a small thing you sometimes take for granted?",
    "What opportunity are you thankful for?",
    "What is one thing about me you noticed recently?",
    "What helped you through a difficult moment?",
    "What is a gift you still enjoy?",
    "What ordinary sound do you find comforting?",
  ],
  Possibility: [
    "What would you do with a surprise day off?",
    "What is a place you want to explore nearby?",
    "What meal should we try making?",
    "What would you like to learn for fun?",
    "What could we do together for under €10?",
    "What is something you would like to start again?",
    "What would your ideal weekend include?",
    "What would you like to photograph?",
    "What book or film would you like to share?",
    "What would you grow in a garden?",
    "What tiny goal would feel good to complete?",
    "What new route would you like to walk?",
    "What would you like to show me from your world?",
    "What would you collect just for pleasure?",
    "What experience would you choose over a gift?",
    "What would you like to make by hand?",
    "What would you do if the weather were perfect?",
    "What could become our next tradition?",
    "What would you like to celebrate soon?",
    "What is a question you would ask your future self?",
  ],
  Reflection: [
    "What helps you feel grounded?",
    "What do you need a little more of today?",
    "What is something you are getting better at?",
    "What does rest look like for you right now?",
    "What is a thought you want to hold onto?",
    "What have you changed your mind about lately?",
    "What is something you want to approach with patience?",
    "What makes you feel most like yourself?",
    "What is one thing you can simplify?",
    "What have you learned about friendship?",
    "What gives you a sense of belonging?",
    "What is a risk you are glad you took?",
    "What does enough mean to you today?",
    "What are you curious about at the moment?",
    "What makes it easier for you to ask for help?",
    "What would you tell yourself a year ago?",
    "What is something you have made peace with?",
    "What do you want to protect time for?",
    "What kind of day leaves you content?",
    "What would help you feel supported this week?",
  ],
});

export const content: Question[] = [
  ...thisOrThatQuestions,
  ...knowMeQuestions,
  ...deepTalkQuestions,
  ...drawingWords,
  ...dailyQuestions,
];
