import type { Question } from "./types.ts";

// Authored building blocks produce distinct, grammatical cards without an AI service.
const choices: Record<string, string[]> = {
  Travel: [
    "A lakeside picnic",
    "A forest cabin",
    "A coastal train ride",
    "A mountain spa",
    "An island ferry",
    "A night market",
    "A desert sunrise",
    "A riverside bike ride",
    "A tiny village",
    "A botanical garden",
    "A rooftop sunset",
    "A street-food tour",
    "A castle visit",
    "A whale-watching boat",
    "A scenic road trip",
    "A hot-air balloon ride",
    "A snowy chalet",
    "A waterfall hike",
    "A vineyard weekend",
    "An old bookshop",
  ],
  Food: [
    "Homemade ramen",
    "Wood-fired pizza",
    "A taco tasting",
    "A cheese board",
    "Breakfast pancakes",
    "Fresh cinnamon rolls",
    "A sushi workshop",
    "A pasta workshop",
    "A dumpling night",
    "A curry night",
    "Chocolate fondue",
    "A strawberry picnic",
    "A farmers-market lunch",
    "A midnight sandwich",
    "A soup and bread night",
    "A homemade ice-cream tasting",
    "A vegetarian barbecue",
    "A tapas evening",
    "A pie-baking date",
    "A waffle brunch",
  ],
  Us: [
    "A pottery date",
    "A karaoke duet",
    "A puzzle night",
    "A photo walk",
    "A dance lesson",
    "A comedy show",
    "A stargazing date",
    "A bookshop date",
    "A painting evening",
    "A mini-golf challenge",
    "A home cinema",
    "A live concert",
    "A board-game café",
    "A letter-writing evening",
    "A climbing date",
    "A homemade treasure hunt",
    "An aquarium visit",
    "A cooking challenge",
    "A shared playlist session",
    "A candle-making class",
  ],
  Lifestyle: [
    "A quiet Sunday",
    "A spontaneous Saturday",
    "A balcony garden",
    "A room full of books",
    "A daily walk",
    "A weekly adventure",
    "An early workout",
    "An evening swim",
    "A cosy kitchen",
    "A creative studio",
    "A pet-friendly home",
    "A travel-friendly lifestyle",
    "A screen-free evening",
    "A gaming evening",
    "A city apartment",
    "A country cottage",
    "A weekly dinner party",
    "A weekend for two",
    "A morning journal",
    "An evening sketchbook",
  ],
  Future: [
    "Learn to sail together",
    "Learn to dance together",
    "Build a little library",
    "Plant a fruit garden",
    "Take a month-long train trip",
    "Make a short film",
    "Renovate a campervan",
    "Write a cookbook",
    "Volunteer abroad",
    "Learn a new language",
    "Create a family tradition",
    "Host an annual reunion",
    "Adopt a rescue animal",
    "Build a tiny cabin",
    "Run a half-marathon",
    "Start a creative project",
    "Visit every national park",
    "Learn photography",
    "Live near the ocean",
    "Live near the mountains",
  ],
  Fun: [
    "A superhero costume",
    "A detective costume",
    "A treasure map",
    "A magic compass",
    "A talking cat",
    "A friendly dragon",
    "A time-travel train",
    "A flying bicycle",
    "A secret treehouse",
    "An underwater café",
    "A robot chef",
    "A tiny personal spaceship",
    "An endless music festival",
    "A floating cinema",
    "A surprise dance battle",
    "A surprise trivia battle",
    "A mystery dinner",
    "A silent disco",
    "A giant pillow fort",
    "A neon bowling night",
  ],
};
export const expandedChoices: Question[] = Object.entries(choices).flatMap(
  ([category, items]) =>
    items.flatMap((a, i) =>
      items
        .slice(i + 1)
        .map((b, j) => ({
          id: `fresh-choice-${category.toLowerCase()}-${i}-${i + j + 1}`,
          game: "this-or-that" as const,
          category,
          prompt: "This or that?",
          optionA: a,
          optionB: b,
        })),
    ),
);

const topics: Record<string, string[]> = {
  Us: [
    "how we celebrate small wins",
    "our everyday rituals",
    "the way we make decisions",
    "our sense of humour",
    "sharing space",
    "feeling appreciated",
    "trying something new together",
    "making time for each other",
    "how we show affection",
    "being a team",
    "our different personalities",
    "time apart",
  ],
  Future: [
    "the home we want to create",
    "a future adventure",
    "our priorities in five years",
    "growing older together",
    "a skill we could learn",
    "the traditions we could start",
    "a project we could build",
    "the places we could live",
    "how we want to spend our weekends",
    "our shared dreams",
    "our next big decision",
    "a slower way of life",
  ],
  Dreams: [
    "a creative ambition",
    "an adventure you keep imagining",
    "the person you hope to become",
    "a place you want to discover",
    "a skill you secretly want to master",
    "your idea of a fulfilling life",
    "something you would make just for joy",
    "a dream you had as a teenager",
    "a chance you would love to take",
    "a life with more freedom",
    "a project you would start tomorrow",
    "a wish you rarely talk about",
  ],
  Childhood: [
    "the games you played as a child",
    "your childhood neighbourhood",
    "your earliest friendships",
    "your favourite family ritual",
    "the stories you grew up with",
    "your first experience of independence",
    "the adults you looked up to",
    "the places you explored",
    "your childhood imagination",
    "your school-day routines",
    "the things you used to collect",
    "a childhood lesson you kept",
  ],
  Memories: [
    "our first adventures",
    "a moment we laughed until it hurt",
    "a place that reminds you of us",
    "a meal we still talk about",
    "a surprise that stayed with you",
    "a difficult day we got through",
    "a song attached to a memory",
    "a journey that changed you",
    "a moment of unexpected kindness",
    "a celebration that felt special",
    "a photo you treasure",
    "an ordinary day you remember",
  ],
  Funny: [
    "our most unlikely business idea",
    "a ridiculous talent show",
    "a holiday with no luggage",
    "our imaginary reality show",
    "a dinner cooked by robots",
    "a day when animals could talk",
    "our secret superhero identities",
    "a wildly impractical house",
    "a surprise comedy routine",
    "a competition we would definitely lose",
    "our imaginary royal titles",
    "a completely unnecessary invention",
  ],
  Vulnerable: [
    "asking for support",
    "feeling truly understood",
    "saying what you need",
    "making a mistake",
    "trusting your own judgment",
    "the pressure to have everything figured out",
    "feeling safe in a relationship",
    "setting a boundary",
    "being honest about a worry",
    "giving yourself permission to rest",
    "accepting a compliment",
    "showing a softer side",
  ],
  Random: [
    "a song that changes your mood",
    "a place where you feel at home",
    "a habit you want to try",
    "a book that stayed with you",
    "a tiny everyday luxury",
    "a conversation you wish you could have",
    "an unusual thing you find beautiful",
    "a skill you admire",
    "a question you never get asked",
    "a sound you love",
    "a piece of advice you disagree with",
    "an unexpectedly good day",
  ],
};
const conversationFrames = [
  (t: string) => `When you think about ${t}, what matters most to you?`,
  (t: string) => `What would you like me to understand about ${t}?`,
  (t: string) => `What is a story you could tell me about ${t}?`,
  (t: string) => `How has your perspective on ${t} changed?`,
  (t: string) => `What surprises you about ${t}?`,
  (t: string) => `What feeling comes up when you imagine ${t}?`,
  (t: string) => `What would you ask me about ${t}?`,
  (t: string) => `What is one thing you want to explore about ${t}?`,
];
export const expandedConversations: Question[] = Object.entries(topics).flatMap(
  ([category, items]) =>
    items.flatMap((topic, i) =>
      conversationFrames.map((frame, j) => ({
        id: `fresh-talk-${category.toLowerCase()}-${i}-${j}`,
        game: "deep-talk" as const,
        category,
        prompt: frame(topic),
      })),
    ),
);

const situations = [
  "a rainy Sunday",
  "a free afternoon",
  "a weekend by the sea",
  "a winter evening",
  "a summer road trip",
  "a visit to a new city",
  "a birthday celebration",
  "a quiet night at home",
  "a surprise day off",
  "a stressful workday",
  "a long train ride",
  "a lazy brunch",
  "a holiday with friends",
  "a first day in a new home",
  "an evening without screens",
  "a visit to a night market",
  "a snowy weekend",
  "a festival weekend",
  "a family gathering",
  "a day in the countryside",
  "a mountain holiday",
  "a spontaneous date",
  "a week with no plans",
  "a nostalgic evening",
  "a seaside picnic",
  "a very early morning",
  "a day with a tiny budget",
  "a celebration of a small win",
  "a weekend without internet",
  "an adventure abroad",
];
const predictionFrames = [
  (t: string) => `What food would I choose for ${t}?`,
  (t: string) => `What music would I put on during ${t}?`,
  (t: string) => `Who would I want to invite to ${t}?`,
  (t: string) => `What would I pack for ${t}?`,
  (t: string) => `What would I photograph during ${t}?`,
  (t: string) => `What small luxury would I want for ${t}?`,
  (t: string) => `What would I do first during ${t}?`,
  (t: string) => `What would I most look forward to during ${t}?`,
  (t: string) => `What would I happily skip during ${t}?`,
  (t: string) => `How would I make ${t} feel special?`,
];
export const expandedPredictions: Question[] = situations.flatMap((topic, i) =>
  predictionFrames.map((frame, j) => ({
    id: `fresh-know-${i}-${j}`,
    game: "do-you-know-me" as const,
    category: "Imagination",
    prompt: frame(topic),
  })),
);

const reflections = [
  "a small act of kindness",
  "something you learned",
  "a conversation you had",
  "a moment outdoors",
  "a moment of calm",
  "something you created",
  "a choice you made",
  "something that made you laugh",
  "a moment of connection",
  "a change in your routine",
  "a memory that came back",
  "a little challenge you faced",
  "something you tried",
  "a moment you felt proud",
  "a moment of courage",
  "a quiet pleasure",
  "a surprise",
  "something you noticed about yourself",
  "a moment you felt supported",
  "something you let go of",
  "a moment of curiosity",
  "a small success",
  "a kind word",
  "a moment of patience",
  "an unexpected encounter",
  "a thought that stayed with you",
  "something that gave you energy",
  "a moment of honesty",
  "a reason to feel grateful",
  "something that made life easier",
];
const dailyFrames = [
  (t: string) => `Think of ${t} from today. What happened?`,
  (t: string) =>
    `Think of ${t} from this week. What would you like to tell me about it?`,
  (t: string) => `When did you last experience ${t}, and how did it feel?`,
  (t: string) => `What did ${t} teach you recently?`,
  (t: string) => `What would you like to remember about ${t} this week?`,
  (t: string) => `How could we make room for ${t} tomorrow?`,
  (t: string) => `What would make ${t} more meaningful for you?`,
  (t: string) => `How does ${t} affect your mood?`,
];
export const expandedDaily: Question[] = reflections.flatMap((topic, i) =>
  dailyFrames.map((frame, j) => ({
    id: `fresh-daily-${i}-${j}`,
    game: "daily-us" as const,
    category: "Reflection",
    prompt: frame(topic),
  })),
);
export const expandedWords: Question[] = [
  "Lighthouse",
  "Astronaut",
  "Watering can",
  "Hammock",
  "Roller skates",
  "Windmill",
  "Seahorse",
  "Snow globe",
  "Treasure chest",
  "Paper plane",
  "Treehouse",
  "Hot-air balloon",
  "Campfire",
  "Dragonfly",
  "Jellyfish",
  "Telescope",
  "Typewriter",
  "Wheelbarrow",
  "Sandcastle",
  "Skateboard",
  "Croissant",
  "Saxophone",
  "Cactus",
  "Origami crane",
  "Gingerbread house",
  "Crystal ball",
  "Roller coaster",
  "Ferris wheel",
  "Lava lamp",
  "Snowmobile",
  "Firefly",
  "Peacock",
  "Chameleon",
  "Flamingo",
  "Octopus",
  "Compass",
  "Acorn",
  "Pretzel",
  "Sundial",
  "Submarine",
  "Parachute",
  "Trombone",
  "Bonsai tree",
  "Beehive",
  "Scarecrow",
  "Dandelion",
  "Dragon",
  "Unicorn",
  "Mermaid",
  "Wizard",
].map((prompt, i) => ({
  id: `fresh-word-${i}`,
  game: "drawing-word",
  category: "Objects",
  prompt,
}));
