export type MoralCard = {
  id: string;
  category: string;
  title: string;
  story: string;
  options: [string, string, string, string];
  discuss: [string, string, string];
  deep?: boolean;
};

const make = (
  id: string,
  category: string,
  title: string,
  story: string,
  options: MoralCard["options"],
  discuss: MoralCard["discuss"],
  deep = false,
): MoralCard => ({ id, category, title, story, options, discuss, deep });

export const moralCards: MoralCard[] = [
  make("ms01", "Loyalty", "The Confidence", "You discover that your closest friend had a brief affair months ago. They insist it ended, they regret it, and their partner knows nothing. That partner is also a friend who has trusted you with difficult things. They are now planning to move in together, and recently said they would want to know about infidelity. Your friend asks you to keep quiet, arguing that one mistake should not define an otherwise caring relationship. You did not witness it yourself, and sharing what you know could end both friendships. What responsibility do you have when silence also shapes someone else’s choice?", ["Tell the partner what you know, so they can decide with the full picture.", "Give your friend a short, clear deadline to tell them first.", "Refuse to carry the secret, but ask the partner what they want to know before sharing details.", "Keep the confidence; the relationship belongs to the two people in it."], ["Does loyalty mean protecting a friend from consequences?", "Would your answer change if they were about to marry?", "How certain would you need to be before speaking?"], true),
  make("ms02", "Career", "The Offer Abroad", "A rare role could transform your career and salary, but it requires a three-year move overseas. Your partner has only recently found work they love, has close family nearby, and feels rooted in the community you built together. The offer expires in three days. Your partner says they will not ask you to refuse, yet admits they probably would not move. You could attempt a long-distance relationship, but neither of you knows how it would feel after the first exciting months. There is no guarantee the role can be delayed or made remote. How do you weigh an individual opportunity against a shared life?", ["Decline; protecting the life you chose together matters more.", "Accept and try long distance, with a plan to revisit it honestly.", "Ask your partner to move, while making room for what they would lose.", "Choose the role and end the relationship rather than asking either person to shrink."], ["What would make a sacrifice feel mutual?", "How long should a couple wait before revisiting the decision?", "Does the higher salary change the moral weight?"], true),
  make("ms03", "Money", "The Uneven Deposit", "You have saved together for a home, but one person has contributed almost twice as much because their income is higher. The lower-earning partner has also taken on more unpaid care and household work. A family member offers a gift that could close the gap, but attaches an expectation that the giver will have a say in where you live. The purchase deadline is approaching, and both of you want the home. Equal ownership feels simple, while unequal ownership seems to recognize the cash contributions but may undervalue invisible work. How should a shared future account for different kinds of contribution?", ["Split ownership according to money contributed.", "Own the home equally; income and care work are both contributions.", "Pause the purchase and agree on a structure together before accepting the gift.", "Accept the gift, but refuse any say over your home even if it means losing it."], ["Which contributions are easiest to overlook?", "Should past unpaid work count in financial agreements?", "When does a gift become control?"], true),
  make("ms04", "Family", "The Holiday Table", "Your partner has been hurt by a parent’s repeated comments about their body and career. The parent apologizes privately but makes a similar remark at every family gathering. A milestone birthday is coming up, and your partner asks you to attend while promising to speak up if it happens again. You know your presence can make the parent feel the family is united, but staying away may turn the event into a conflict your partner then has to explain. The parent is aging and the family says there may not be many celebrations left together. What does support look like when the boundary belongs to your partner?", ["Go, and let your partner decide how to handle the parent.", "Go only after agreeing together on how you will respond if it happens again.", "Stay home to show that the repeated disrespect has a real consequence.", "Speak to the parent beforehand, even if your partner did not ask you to."], ["When is intervening supportive and when is it taking over?", "Does family history soften or strengthen a boundary?", "What would make an apology meaningful?"], true),
  make("ms05", "Privacy", "The Open Laptop", "While borrowing a laptop to print a ticket, you see a message preview that suggests your partner has been discussing a serious worry with someone else. You do not open the conversation, but the few visible words leave you concerned that they may be hiding something that affects a decision you are making together. Your partner has always valued keeping friendships private, and you both agreed not to read each other’s messages. You could ask directly and admit what you saw, or wait until they choose to tell you. Is a glimpse enough to justify breaking the privacy agreement further?", ["Tell your partner exactly what appeared and ask about it.", "Ask a broad, honest question about the worry without mentioning the preview.", "Leave it alone; a message preview is not permission to investigate.", "Ask the friend privately, because the decision could affect you both."], ["Is privacy still important when a secret affects both people?", "Does admitting the accidental glimpse change the trust?", "What makes a question feel safe rather than interrogating?"], true),
  make("ms06", "Truth", "The Kind Review", "Your partner is proud of a project they have worked on for months and asks for honest feedback before sharing it publicly. You notice a flaw that might be fixed, but you also know they are tired and have been doubting themselves. The flaw is not dangerous or costly; it is simply the part people may notice first. They say they want honesty, though previous blunt feedback from others has stayed with them for a long time. You could name the issue directly, soften it with praise, or focus on what is already working. What does honesty owe to timing and care?", ["Name the flaw clearly and suggest a concrete fix.", "Ask whether they want encouragement or detailed critique right now.", "Share the concern gently, after naming what works and why.", "Say nothing unless they ask for another review; they have already made their choice."], ["Can kindness change the truth, or only its delivery?", "When does reassurance become misleading?", "Would you want the same feedback in their position?" ]),
  make("ms07", "Friendship", "The Repeated Cancellation", "A close friend has cancelled plans with your partner for the third time, each time at the last minute. Your partner feels dismissed and asks whether you will still go to a group dinner where that friend will be. The friend says they are overwhelmed and did not mean harm, but has not contacted your partner to explain. You care about both people and do not want to turn a scheduling pattern into a loyalty test. Going may appear to excuse the behavior; staying away may make your partner responsible for a conflict they did not create. How should you respond to a pattern without deciding someone else’s friendship?", ["Go to the dinner, but tell the friend privately that the pattern hurt your partner.", "Skip the dinner until the friend reaches out and repairs things directly.", "Ask your partner what support they want, then follow their lead.", "Invite the friend to talk with both of you before deciding about the dinner."], ["At what point does a pattern matter more than intent?", "Should a partner take sides in a friendship conflict?", "What would a real repair look like?" ]),
  make("ms08", "Technology", "The Helpful Assistant", "You are setting up a smart assistant at home. One person wants to connect calendars, voice recordings, and location sharing because it would make planning easier. The other is uneasy that recordings could be stored or that one person might see private appointments. The company’s controls are difficult to understand, and the device is already bought. Neither person has something specific to hide, but each values a different kind of safety. A convenient setup could save time every day; turning features off could make the device less useful. How much convenience is worth sharing by default?", ["Enable the features and trust each other with the shared access.", "Use only the features both people understand and actively want.", "Return the device until you can agree on its privacy settings.", "Let each person choose settings for their own accounts and devices."], ["Does having nothing to hide make privacy less important?", "Who should control shared technology in a home?", "Would a clearer privacy policy change your answer?" ]),
  make("ms09", "Future", "The Different Timeline", "One of you is ready to start trying for a child within a year; the other wants several more years to travel, build savings, and feel more settled. Neither is uncertain about caring for a child, but the timing matters deeply to each person. Friends offer confident advice, and family members are already asking questions. Waiting could bring more stability, but it might also mean one partner spends years feeling that an important hope is postponed. Moving sooner could create joy alongside anxiety. There is no compromise that makes the calendar feel neutral. What should a couple do when both timelines are sincere?", ["Start trying sooner because a shared family matters most.", "Wait until both feel ready, even if the delay is difficult.", "Set a date to revisit the decision with specific conditions, not a vague promise.", "Admit the difference may be fundamental before making commitments."], ["What does 'ready' mean beyond money or age?", "When does waiting become a decision of its own?", "How can hope be discussed without pressure?"], true),
  make("ms10", "Social Media", "The Private Milestone", "Your partner shares a photo celebrating a personal milestone. You are visible in the picture, but they did not ask before posting it. The image is flattering and harmless to most people, yet you prefer to keep parts of your life offline, especially while work colleagues follow the account. Your partner says sharing joy is part of how they connect with friends, and deleting it now would feel like being told they did something wrong. You do not want to control their account, but you want a say when your image or private news is involved. What boundary is fair?", ["Ask them to remove it because your image should not be shared without consent.", "Leave it up this time, then agree on a rule for future posts.", "Ask them to limit the audience rather than delete the post.", "Accept that the post is theirs to share and adjust your own privacy settings."], ["Is consent different for a shared photo and a personal milestone?", "How can a boundary avoid turning into account control?", "What would repair the surprise?" ]),
  make("ms11", "Relationship", "The Separate Weekend", "You have planned a long weekend together for months, but your partner has been invited to a rare reunion with friends they have not seen since moving away. The dates overlap, and the reunion cannot be repeated easily. Your booking can be changed for a fee, and you had pictured the trip as a chance to reconnect after a busy season. Your partner offers to skip the reunion, but you can tell they would regret it. You want to be chosen, yet you do not want their choice to become a test. How do you make room for both closeness and independence?", ["Keep the original trip; commitments deserve protection.", "Change the booking and encourage your partner to attend the reunion.", "Split the weekend so each of you gets part of what matters.", "Ask your partner to decide, then discuss the disappointment without punishment."], ["When does flexibility feel generous rather than one-sided?", "Should a prior plan outweigh a rare opportunity?", "How could you reconnect another way?" ]),
  make("ms12", "Money", "The Family Loan", "Your partner’s sibling asks for a substantial loan after losing work. Your shared savings could cover it, but the money was meant for a home repair and neither of you has agreed how much to lend family. Your partner wants to help immediately and believes the sibling will repay it. You worry that an unpaid loan could create resentment, but refusing may leave someone you care about without a safety net. The sibling has not shared a budget or repayment plan, and asking for one feels cold. Which obligation should guide the decision?", ["Lend the full amount; family should be able to rely on each other.", "Offer a smaller amount you could accept as a gift.", "Wait until you and your partner agree on a plan and the sibling’s needs.", "Decline to use shared savings but support your partner in helping personally."], ["Should a loan to family be treated as a gift?", "How much say should each partner have over shared savings?", "What support is possible besides money?" ]),
  make("ms13", "Loyalty", "The Unflattering Story", "At dinner, a friend tells an embarrassing story about your partner that is technically true but leaves out context. Everyone laughs, including your partner, though you notice they go quiet afterward. The friend has been under stress and often uses humor to connect. Challenging them in front of the group could make your partner the center of attention; saying nothing may signal that the joke was fine. Later, your partner says they do not want you to make a scene but admits it bothered them. How do you respect that request while showing you heard them?", ["Let the moment pass and check in privately with your partner.", "Gently redirect the conversation next time without naming the conflict.", "Tell the friend privately that the story crossed a line.", "Speak up in the moment, even if it draws attention, so the group understands."], ["What is the difference between defending and speaking over someone?", "Should intent affect how you address a hurtful joke?", "What response would help without making it larger?" ]),
  make("ms14", "Career", "The Work Dinner", "A promotion depends partly on being available for evening events. One invitation falls on the only night your partner can visit a close relative who is unwell. The visit can be moved, but the relative has become harder to reach and the opportunity at work may not return soon. Your partner says they understand the stakes but feels that work has been taking every open evening. You could attend briefly, decline, or invite them along, though the event is mostly professional. What does ambition ask of a shared life, and where should its limits be?", ["Attend because the promotion could improve your future together.", "Decline this event and tell work your personal commitment comes first.", "Attend briefly, then join your partner for the rest of the evening.", "Ask your partner to choose which evening matters more to them."], ["How often can an exception happen before it becomes a pattern?", "Should career sacrifices be shared equally?", "What would a fair boundary at work look like?" ]),
  make("ms15", "Privacy", "The Location Request", "A partner asks to turn on continuous location sharing after a difficult commute and a frightening news story. The other person is comfortable sharing arrival times but dislikes being trackable all day. There has never been jealousy or controlling behavior, and the request is framed as reassurance rather than suspicion. Still, a setting that begins as temporary may become part of the relationship without another conversation. A simple check-in text takes more effort but feels less intrusive. How do you distinguish care from a habit of monitoring?", ["Share location continuously because reassurance is a reasonable act of care.", "Share only during trips or for a defined period, then review the choice.", "Decline location sharing and agree on a different safety check-in.", "Try it for a week, with a clear agreement that either person can turn it off."], ["What would make consent to sharing feel freely given?", "Does a safety concern justify a lasting privacy change?", "How could you revisit the boundary?" ]),
  make("ms16", "Truth", "The Missing Detail", "Your partner asks whether you enjoyed a gathering with their friends. You did enjoy parts of it, but one friend repeatedly dismissed your work and made you feel unwelcome. Your partner had been excited for you to get along with everyone and is already worried that moving cities has made it harder to build community. A simple yes would spare a difficult conversation tonight, while a blunt no could make the whole evening feel like a failure. The friend may not realize how they came across. How do you answer honestly without turning one evening into a verdict?", ["Say you enjoyed it overall, but explain the moments that felt uncomfortable.", "Ask if they want the full answer now or just how you are feeling tonight.", "Say you had a good time to protect their excitement.", "Be direct that you do not want to spend time with that friend again."], ["Is tactful timing honest, or avoidance?", "Should your partner address the friend?", "How specific should feedback be?" ]),
  make("ms17", "Family", "The Unwelcome Guest", "A relative who previously made cruel remarks wants to stay with you for two weeks while looking for work. Your partner feels unsafe around them and does not want them in your shared home. You believe the relative has changed and has nowhere else to go. A hotel would be expensive, but the relative has not apologized directly and has not said how they will behave differently. Refusing could create a lasting family rift; agreeing could make your home feel less like a refuge to your partner. What obligations come with sharing a home?", ["Decline the stay; a shared home requires two willing hosts.", "Offer a short stay with clear ground rules and an exit plan.", "Help find another place, even if it costs you more.", "Invite the relative only after they acknowledge the harm directly to your partner."], ["Who gets final say over a shared home?", "Can changed behavior count without an apology?", "What would make a boundary enforceable?" ], true),
  make("ms18", "Future", "The City Choice", "One partner receives a chance to move to a city where they have always wanted to live. The other has a strong support network where you are now and has recently begun caring for a parent who needs regular help. Moving could bring new opportunities and the parent says they do not want to hold anyone back, but practical support would become harder. Staying would protect stability while leaving one partner wondering what they gave up. You have not decided whether your relationship should be the main factor in a move. How do you decide whose roots matter most?", ["Move together and arrange new support for the parent.", "Stay for now while the caregiving need is immediate.", "Try a time-limited move with a plan to return if it is not sustainable.", "Let the person with the opportunity move alone and revisit the relationship later."], ["How do you measure an opportunity that may not return?", "Should family care shape a couple’s location?", "What would make a trial period feel fair?" ], true),
  make("ms19", "Technology", "The Old Photos", "A partner finds old intimate photos from a past relationship backed up on a shared tablet. The photos were made consensually at the time, but the former partner may not know copies remain in a cloud account used by both of you. One person wants to delete everything immediately; the other feels that deleting a past does not solve the larger question of what was shared or stored. No one is threatening to post them, but keeping them feels uncomfortable. What does responsibility to a former partner require when privacy and memory overlap?", ["Delete the photos and backups now, without reopening them.", "Ask the former partner whether they want the copies deleted, then follow their preference.", "Remove them from shared devices and review cloud backups together.", "Keep them in a private archive; consensual memories need not be erased."], ["Does consent to create an image include indefinite storage?", "Whose privacy is at stake now?", "How much should a current partner be involved?" ], true),
  make("ms20", "Friendship", "The Wedding Invitation", "Your partner is invited to the wedding of an ex who remains part of a shared friend group. You trust your partner, and they have been open about the past. The wedding is out of town, and most friends plan to stay together for the weekend. You are welcome to come, but you know you would feel awkward and would rather not spend the trip there. Asking your partner not to go could isolate them from the group; going along may make your discomfort everyone’s problem. What would you consider a fair way to handle the invitation?", ["Go together and treat the weekend as a chance to meet the group.", "Let your partner go alone, and agree on boundaries that feel respectful.", "Ask your partner to decline because this event is too intimate with an ex.", "Talk through the discomfort and decide together without making attendance a loyalty test."], ["What makes a boundary protective rather than controlling?", "Would your answer change if you had met the ex?", "What reassurance would actually help?" ]),
  make("ms21", "Money", "The Secret Savings", "You learn your partner has kept a private savings account for years. They say it began when a previous relationship left them financially vulnerable and grew into a sense of safety. Your shared bills are paid fairly and there is no debt hidden from you, but you had assumed all savings goals were shared. You feel excluded from a major part of your future planning. Your partner fears that combining everything would mean losing independence. Is financial privacy compatible with building a life together?", ["Respect the account as personal security, and agree on shared goals separately.", "Ask for full transparency before making any larger joint commitments.", "Set a shared savings target while allowing each person private funds.", "Combine savings, but give both partners equal control over withdrawals."], ["What financial details should partners share?", "Can privacy and trust coexist around money?", "How do past experiences shape shared decisions?" ], true),
  make("ms22", "Relationship", "The Unbalanced Care", "For months, one partner has supported the other through a difficult period: appointments, meals, reminders, and emotional check-ins. The person receiving care is grateful but has begun to feel managed. The caregiving partner is tired and misses being spontaneous, yet worries that asking for less will sound selfish. There is no clear finish date, and outside help could be arranged but would require money and uncomfortable conversations. Both love each other, but the current arrangement no longer feels freely chosen. How should care change when it starts to exhaust the person giving it?", ["Keep helping; a difficult period is when partnership matters most.", "Agree on specific tasks and bring in outside help for the rest.", "The person receiving care should take over what they safely can, even if it is slower.", "Pause some support now and talk honestly about what each person can sustain."], ["When does care become control?", "What kind of help is difficult to ask for?", "How can gratitude avoid becoming obligation?" ], true),
  make("ms23", "Loyalty", "The Reference", "A former colleague asks your partner to be a job reference. The colleague was kind personally but repeatedly took credit for other people’s work. Your partner never confronted them and knows a positive reference could help them get a role they badly need. The hiring manager will ask about collaboration, and your partner can either be enthusiastic, decline, or give a measured account. You worry a dishonest endorsement could put a team in a difficult position, while a candid one could affect the colleague’s livelihood. What does fairness look like when the truth has consequences?", ["Give an honest, balanced reference that names both strengths and concerns.", "Decline without explaining, since the relationship is complicated.", "Offer a positive reference focused only on work the colleague did well.", "Tell the colleague you cannot recommend them unless they address the past behavior."], ["Is silence a kind of reference?", "Should private character affect a professional endorsement?", "How much certainty do you need before raising a concern?" ]),
  make("ms24", "Truth", "The Surprise Party", "Your partner dislikes being the center of attention and once asked for a quiet birthday. Friends are planning a surprise gathering because they believe your partner secretly enjoys it. You could help them make it happen, warn your partner, or suggest a smaller plan without revealing everything. The friends have already booked a room and say the intention is loving. You know your partner may smile to avoid disappointing people even if they feel overwhelmed. Does preserving a surprise matter when you have reason to think it conflicts with a stated boundary?", ["Help make the surprise, trusting the friends know them too.", "Tell the friends not to do it and plan something your partner asked for.", "Ask your partner about birthday plans without revealing the surprise.", "Suggest a small gathering with an easy way to leave early."], ["Can a good intention excuse ignoring a clear preference?", "How might your partner feel pressured to perform gratitude?", "What makes a celebration feel personal?" ]),
  make("ms25", "Career", "The Public Credit", "A presentation your partner created is being praised by a senior colleague who delivered it. The colleague says your partner's name was left off by accident and promises to correct it later. Your partner is early in their career and fears being labeled difficult if they raise the issue. You know the work mattered and feel angry on their behalf, but your partner has asked you not to email anyone. The recognition could affect a promotion decision. Should support mean staying beside them, or helping them claim credit even when they hesitate?", ["Respect their request and help them plan a direct conversation.", "Encourage them to write a calm note documenting their contribution.", "Contact the colleague yourself because the omission is unfair.", "Let it go this time; protecting their reputation may matter more."], ["When does advocacy become taking control?", "How would you weigh short-term comfort against career impact?", "What evidence would make a correction easier?" ]),
  make("ms26", "Family", "The Inheritance", "A relative leaves a larger inheritance to one partner than to their siblings, citing years of practical help. The recipient wants to use it for a shared home; the other partner worries that accepting it will deepen family resentment or make them feel indebted to someone who is gone. The siblings have not objected, but one has quietly asked whether the decision was fair. The money could ease a major financial strain for both of you. Is it respectful to accept a choice someone made, or responsible to question an unequal benefit?", ["Accept it as the relative’s considered decision.", "Set aside a portion for the siblings before making plans.", "Ask the family to discuss the inheritance openly before spending it.", "Keep it separate from shared finances so it does not define your choices."], ["Does accepting unequal treatment make you responsible for it?", "Should inheritance stay personal or become shared?", "What would fairness mean when intent cannot be revisited?" ], true),
  make("ms27", "Privacy", "The Shared Calendar", "One partner wants every appointment and plan in a shared calendar because missed details have caused friction. The other has confidential therapy sessions and private commitments they do not want to explain. The calendar can mark time as unavailable without naming the reason, but the first partner worries that vague blocks will make planning harder. Neither person has used schedule information to monitor the other. You both want fewer surprises, yet a shared tool could quietly turn into an expectation of total visibility. How much detail is necessary for coordination?", ["Share every appointment; openness makes planning easier.", "Share availability only, keeping titles private unless they affect both of you.", "Use separate calendars and agree on a weekly planning conversation.", "Let each person choose which events are shared, even if that means more coordination."], ["Is availability enough information for partnership?", "What kinds of privacy should remain ordinary?", "Would the same rule apply to finances or messages?" ]),
  make("ms28", "Friendship", "The Borrowed Car", "A friend borrows your partner’s car and returns it with a new scrape, saying it was already there. You noticed the car was clean before the loan, but there is no photo or proof. The repair is affordable, though inconvenient. Your partner says the friendship matters more than a small dispute and wants to let it go. You think avoiding the conversation may create resentment, especially because this friend has borrowed things several times. How do you balance generosity with a pattern that may be taking advantage?", ["Let the scrape go; preserving a friendship is worth more than the cost.", "Ask the friend to contribute to the repair without accusing them of lying.", "Stop lending the car, but do not bring up the scrape.", "Tell the friend directly what you observed and ask them to make it right."], ["When does generosity become enabling?", "Does proof matter if trust has already shifted?", "Who gets to decide about a shared possession?" ]),
  make("ms29", "Technology", "The Training Data", "A partner uses an AI writing tool to draft a message about a private conflict between you. They say they removed names and found the suggestions useful. You feel uneasy that intimate details may have been sent to a service, even if the service says it may not identify you. Your partner feels the tool helped them express something they could not say out loud. The message has not been shared, and neither of you agreed on rules for using outside tools with personal information. What boundary should apply to stories that belong to both of you?", ["Accept the use of the tool; the details were anonymized and it helped.", "Agree that private relationship details stay out of external tools unless both consent.", "Ask your partner to delete the chat and explain what was shared.", "Let each person use tools privately, but not include identifying or intimate details."], ["Can anonymized stories still belong to two people?", "What would informed consent look like here?", "Would a therapist or trusted friend feel different?" ], true),
  make("ms30", "Future", "The Different Risk", "You have an opportunity to start a small business together. One partner is excited to invest most of the savings and work evenings for a year; the other prefers a stable income and worries that a failed launch would affect housing plans. Both understand the risks, but one thinks waiting means missing a rare moment, while the other sees a plan built on hope rather than evidence. You could test the idea part-time, though that might slow it down. How much risk should one person be able to ask a couple to share?", ["Invest now while the opportunity is strongest.", "Run a smaller trial with a budget limit and a review date.", "Keep the savings protected and revisit once the business has paying customers.", "Let the interested partner pursue it with personal funds and time."], ["Which risk belongs to the couple and which belongs to one person?", "How can caution support an ambition?", "What evidence would change your view?" ], true),
  make("ms31", "Relationship", "The Uneven Move", "You move to support your partner’s new role, leaving behind friends and familiar routines. Six months later you are struggling to find work and feel lonely. Your partner is thriving and says the move was a choice you made together, but also offers to search for roles in your old city. Moving back could disrupt their progress and make both of you wonder whether the sacrifice was temporary. Staying may be right eventually, but you do not want gratitude to silence a real need. How do you revisit a joint choice without treating it as blame?", ["Stay for a set period and make a concrete plan to build community.", "Move back together because the arrangement is harming one partner.", "Let the struggling partner return for a while and maintain the relationship remotely.", "Decide together based on what each person needs now, not on the original promise."], ["How often should a shared decision be reconsidered?", "Does choosing something once make it fair forever?", "What would repair feel like to the person who moved?" ], true),
  make("ms32", "Money", "The Wedding Budget", "You are invited to a destination wedding for a close friend. The trip would use money saved for a shared goal, and only one partner is close to the couple. The friend says they understand if you cannot come, but your partner worries that declining will change the friendship. You could attend alone, though the travel is long and the other partner would spend the weekend alone. The cost is manageable but not trivial. Is a shared budget meant to support individual relationships, or should both people agree on every large expense?", ["Use the shared savings and attend together.", "Attend alone and pay your own share from personal money.", "Decline because the shared goal takes priority right now.", "Agree on a spending threshold each person can use independently."], ["What counts as a large expense for a couple?", "Should closeness to the friend change the decision?", "How would the answer change if the wedding were nearby?" ]),
  make("ms33", "Truth", "The Unsent Apology", "Someone who hurt your partner years ago sends you a long apology and asks you to pass it along. Your partner has never asked you to cut contact, but they also never wanted to hear from this person again. The apology appears sincere and names specific harm, yet it includes a request to be forgiven. Passing it on could give your partner a choice, or force them to relive something they had left behind. Ignoring it keeps the boundary intact but makes you the person holding the message. What should you do with an apology that was not addressed to you?", ["Pass it on without comment so your partner can decide.", "Tell the sender not to contact you again and leave your partner undisturbed.", "Ask your partner whether they want to receive messages from this person.", "Explain to the sender that an apology does not create an obligation to respond."], ["Can an apology be a burden when it arrives uninvited?", "Who controls access to someone else's attention?", "What makes an apology accountable?" ]),
  make("ms34", "Family", "The Care Decision", "A parent needs increasing help and assumes one adult child will provide most of it because they live closest. Your partner loves the parent, but the expectation is already affecting work and rest. Other siblings offer money but cannot visit often. A care service could help, though the parent dislikes strangers and the cost would reduce savings. Your partner says family should take care of family, while you see one person carrying a burden that belongs to several. How do you honor care without letting closeness become an automatic assignment?", ["Take on the help because being nearby makes it practical.", "Set a schedule that includes siblings and paid support.", "Ask the parent to accept professional help before providing more care.", "Let your partner decide what they can offer, while protecting shared time and finances."], ["Who gets to define what family care requires?", "Does proximity create responsibility?", "What would an equitable arrangement look like?" ], true),
  make("ms35", "Loyalty", "The Group Chat", "A group chat makes increasingly cruel jokes about a mutual friend who is not present. Your partner says the jokes are a way the group vents and that confronting everyone could isolate you both. The friend has previously laughed along when present, but you do not know whether they have seen these messages. You could leave the chat, challenge the group, message the friend, or say nothing and keep access to plans and information. Each choice affects different relationships. What kind of loyalty matters when no one is watching?", ["Call out the jokes in the chat and explain why they cross a line.", "Message the person privately to ask how they feel about the group dynamic.", "Leave the chat without making a public statement.", "Stay in the chat but refuse to join in, avoiding escalation."], ["Does silence make you part of a group's behavior?", "Would public confrontation protect or embarrass the friend?", "What would you hope a friend did for you?" ]),
  make("ms36", "Privacy", "The Medical Update", "A close relative asks your partner for details about a diagnosis that affects both of you, including medication and future plans. Your partner wants to share enough for the family to understand why you may need support. You are comfortable sharing the diagnosis but not every detail. The relative is loving and likely to help, yet family information tends to spread quickly. Your partner feels that keeping everything private may make it harder to ask for practical help. How should a couple decide what personal information becomes family knowledge?", ["Share the details because support is worth the loss of privacy.", "Agree together on a short update that explains needs without medical specifics.", "Let the person diagnosed decide what is shared, even if the partner needs support too.", "Ask the relative to keep the information private before sharing more."], ["Which parts of a shared situation remain personal?", "How do you ask for help while protecting detail?", "What if a family member breaks confidence?" ], true),
  make("ms37", "Career", "The Night Shift", "A promotion requires six months of night shifts. The extra income would help with a financial goal, but your routines would barely overlap. One partner is eager to take it and believes the strain will be temporary; the other is worried that recent distance is already difficult. There is no way to know whether the role leads to better hours afterward. Declining may close a rare path forward, while accepting could turn shared time into something scheduled and scarce. How do you weigh a temporary sacrifice when its end is uncertain?", ["Take the role and protect one regular shared ritual each week.", "Decline until the relationship feels more settled.", "Accept only after agreeing on a review point and signs that the arrangement is too much.", "Ask the employer for a different schedule, even if it risks the offer."], ["What makes a sacrifice temporary in practice?", "How should a couple measure the cost of lost time?", "Would more income meaningfully change the decision?" ]),
  make("ms38", "Friendship", "The Shared Secret", "A friend tells you they are considering leaving a long relationship and asks you not to tell anyone. Your partner is close to both people and already suspects something is wrong. You do not want to lie if asked directly, but revealing the confidence could damage trust before your friend is ready. The partner may be making major plans with the couple, unaware that the relationship could soon change. You are not responsible for deciding whether the friend should stay, but keeping quiet puts you in an uncomfortable position. How do you protect trust without becoming a messenger?", ["Keep the confidence and tell your partner you cannot discuss the friend’s private life.", "Encourage the friend to speak honestly with their partner soon.", "Tell your partner only that something is difficult, without sharing details.", "Refuse to hold the secret and ask the friend to release you from it."], ["Can you protect a confidence without lying?", "When does a secret begin to affect other people unfairly?", "What boundaries would help next time?" ]),
  make("ms39", "Technology", "The Smart Doorbell", "A doorbell camera records visitors and saves clips in an account one partner controls. It has helped identify missed deliveries, but it also recorded a private conversation on the front step and captured a neighbor in distress. The account owner says the recordings are automatically deleted after a month. The other partner did not realize the audio was on and feels that a home device has changed the privacy of anyone who visits. Turning it off seems safer but removes a feature that offers peace of mind. What consent do people owe to guests and neighbors?", ["Keep the camera but turn off audio and shorten storage time.", "Tell visitors that recording is active and let them choose where to talk.", "Disable the camera; convenience does not justify recording others.", "Keep it active because public-facing areas carry less expectation of privacy."], ["What should guests be told before entering a recorded space?", "Does a security benefit justify incidental recording?", "Who is responsible for the account and its clips?" ], true),
  make("ms40", "Future", "The Last-Minute Plan", "You have agreed to spend a quiet weekend together, but a once-in-a-lifetime event appears nearby. Tickets are scarce, expensive, and available only for the original weekend. One partner sees the event as an exciting memory; the other was counting on rest after a demanding month and feels tired of plans changing. Both positions are real, and neither person chose the timing. Going could create a story you will remember; staying could protect the kind of care that does not look exciting. What does making memories together ask of a couple?", ["Go to the event and make the quiet time another weekend.", "Keep the original plan; rest was the reason you protected the time.", "Ask whether a shorter version of the event can fit around real rest.", "Let the person who cares more about the event decide, without keeping score."], ["Which is harder to replace: a rare event or protected rest?", "How do changing plans affect trust over time?", "What would compromise look like if neither wants to yield?" ]),
];

export type RankSet = { id: string; category: string; title: string; items: [string,string,string,string,string]; mode?: "draw" | "describe" };
const r = (id: string, category: string, title: string, items: RankSet["items"], mode?: RankSet["mode"]): RankSet => ({ id, category, title, items, mode });
export const rankSets: RankSet[] = [
  r("rd01","Travel","Your perfect escape",["A tropical island","A slow road trip","A lively city","A quiet mountain cabin","A small coastal town"]),
  r("rd02","Date","The ideal date night",["A candlelit dinner","Cooking something new","A film and blankets","A surprise adventure","A long walk together"]),
  r("rd03","Home","One dream-home feature",["A generous kitchen","A private garden","A cozy cinema","A sunlit studio","A reading nook"]),
  r("rd04","Future","An unexpected €10,000",["Travel somewhere far","Make home more comfortable","Invest for later","Learn a new skill","Share an experience"]),
  r("rd05","Weekend","Your perfect Saturday",["Out before sunrise","Coffee and no plans","Friends around a table","A spontaneous day trip","A peaceful day at home"]),
  r("rd06","Food","A memorable dinner",["Fresh pasta together","A tiny tasting menu","Street food after dark","A picnic outdoors","Breakfast for dinner"]),
  r("rd07","Lifestyle","A good everyday life",["More unhurried time","A close community","Room to explore","Financial calm","Work that matters"]),
  r("rd08","Couple","What makes love feel strong",["Honest conversations","Small daily care","Shared laughter","Space to grow","Showing up in hard times"]),
  r("rd09","Travel","One journey to take together",["Northern lights","A train across Europe","Island hopping","A cabin in the Alps","A food tour abroad"]),
  r("rd10","Date","A small unexpected treat",["Flowers at home","A handwritten note","Their favorite snack","A planned evening","An hour of doing nothing"]),
  r("rd11","Home","Your ideal evening corner",["A deep sofa","A window seat","A record player","Soft warm lighting","A table for two"]),
  r("rd12","Future","A year with one extra day",["Visit family","Take a class","Go somewhere new","Rest without guilt","Make something by hand"]),
  r("rd13","Weekend","A shared mini-adventure",["Find a hidden café","Follow a scenic trail","Take the wrong train on purpose","Explore a neighborhood","Drive until something looks good"]),
  r("rd14","Food","A perfect picnic basket",["Fresh bread and cheese","Fruit and something sweet","Warm pastries","A homemade dish","Cold drinks and small snacks"]),
  r("rd15","Lifestyle","A personal superpower",["Stay calm under pressure","Make anyone laugh","Learn anything quickly","Notice what people need","Turn ideas into plans"]),
  r("rd16","Couple","A ritual worth keeping",["A weekly walk","A phone-free meal","A goodnight call","A monthly day trip","A shared playlist"]),
  r("rd17","Travel","Where to spend a rainy day",["A museum","A tiny bookshop","A long lunch","A covered market","A train to somewhere else"]),
  r("rd18","Date","A shared first",["Take a dance class","Try a new cuisine","See a live show","Camp under the stars","Make something together"]),
  r("rd19","Home","A slow Sunday morning",["Coffee in bed","Fresh pancakes","A walk for pastries","Music while tidying","A book and quiet"]),
  r("rd20","Future","A thing to learn as a pair",["A language","Pottery","A new recipe","Dancing","Growing plants"]),
  r("rd21","Weekend","Choose your afternoon",["A lakeside swim","A long lunch with friends","A new game","A scenic drive","A nap with no alarm"]),
  r("rd22","Food","Choose one comfort",["A bowl of noodles","A warm pie","A perfect sandwich","A big breakfast","Chocolate after dinner"]),
  r("rd23","Lifestyle","A little more of this",["Time outside","Creative energy","A predictable routine","Surprising conversations","A sense of progress"]),
  r("rd24","Couple","A thoughtful way to reconnect",["Ask a better question","Share a funny memory","Make a small plan","Say what you appreciate","Sit close without talking"]),
  r("rd25","Travel","A place to wake up",["A cabin by water","A lively old city","A quiet village","A desert under stars","A room above a bakery"]),
  r("rd26","Date","A low-key celebration",["Cook a favorite meal","Revisit your first date","Open a good bottle","Watch the sunset","Exchange small letters"]),
  r("rd27","Home","A balcony worth having",["Herbs and flowers","A chair for two","Soft lights at night","A tiny table","Room for a hammock"]),
  r("rd28","Future","A free month together",["Travel slowly","Volunteer locally","Finish a creative project","Visit loved ones","Stay home and rest"]),
  r("rd29","Weekend","A shared creative project",["Build a playlist","Take film photos","Make a small garden","Paint a room","Create a recipe book"],"draw"),
  r("rd30","Couple","Sketch the place you feel most yourselves",["A familiar café","A favorite room","A quiet park","Somewhere far away","A place still to discover"],"draw"),
];

export type BombCard = { id: string; module: string; category: string; prompt: string; options: string[]; answer?: string; hints?: [string,string] };
export const bombCards: BombCard[] = [
  {id:"rb-sync-01",module:"SYNC",category:"Sync",prompt:"An unexpected €5,000 lands in your shared account. What feels most like the two of you?",options:["Plan a trip","Save it","Invest it","Make home better"]},
  {id:"rb-sync-02",module:"SYNC",category:"Sync",prompt:"You both get a free Saturday in a new city. First move?",options:["Find coffee","Explore on foot","Book a museum","Ask a local"]},
  {id:"rb-sync-03",module:"SYNC",category:"Sync",prompt:"Your evening suddenly clears. Pick a shared reset.",options:["Cook together","Go outside","Choose a film","Call a friend"]},
  {id:"rb-know-01",module:"KNOW ME",category:"Partner sense",prompt:"Predict your partner: the perfect free Saturday starts with…",options:["A slow morning","A day trip","Movement and good food","Seeing friends"]},
  {id:"rb-know-02",module:"KNOW ME",category:"Partner sense",prompt:"What would your partner choose for a small celebration?",options:["A favorite meal","A new experience","A quiet night","A spontaneous outing"]},
  {id:"rb-order-01",module:"ORDER IT",category:"Shared priorities",prompt:"Rank these from most to least important for a lovely weekend.",options:["Rest","Novelty","Good food","Time together"]},
  {id:"rb-order-02",module:"ORDER IT",category:"Shared priorities",prompt:"Put these ingredients for a great date in your order.",options:["Surprise","Conversation","Comfort","A little adventure"]},
  {id:"rb-one-word-01",module:"ONE WORD",category:"One word",prompt:"Describe your relationship lately in one word.",options:[]},
  {id:"rb-one-word-02",module:"ONE WORD",category:"One word",prompt:"Choose one word you both want more of next month.",options:["Calm","Adventure","Laughter","Closeness"]},
  {id:"rb-comm-01",module:"COMMUNICATE",category:"Communication puzzle",prompt:"Find the colour that satisfies both clues.",options:["Red","Blue","Green","Yellow"],hints:["It is not red. It sits next to blue.","Green is incorrect. Blue is not next to yellow."],answer:"Blue"},
  {id:"rb-comm-02",module:"COMMUNICATE",category:"Communication puzzle",prompt:"Which little signal fits both clues?",options:["Moon","Star","Heart","Sun"],hints:["It is not the heart. It comes before the sun in this order: moon, star, sun.","It is the brightest shape, but not the sun."],answer:"Star"},
  {id:"rb-dont-01",module:"DON'T SAY IT",category:"Describe & guess",prompt:"Describe a city of canals without saying the words on your card.",options:["Venice","Prague","Lisbon","Amsterdam"],answer:"Venice"},
  {id:"rb-dont-02",module:"DON'T SAY IT",category:"Describe & guess",prompt:"Help your partner find the answer without using the obvious clues.",options:["A lighthouse","A greenhouse","A bookshop","A train station"],answer:"A greenhouse"},
  {id:"rb-fast-01",module:"FAST AGREEMENT",category:"Fast agreement",prompt:"Quick-fire: choose together before the timer ends.",options:["Mountains / Beach","Morning / Night","Money / Time","Plan / Spontaneous"]},
  {id:"rb-fast-02",module:"FAST AGREEMENT",category:"Fast agreement",prompt:"No overthinking. Four tiny choices, one shared rhythm.",options:["Sweet / Savory","City / Nature","Stay in / Go out","Photos / Memories"]},
  {id:"rb-memory-01",module:"MEMORY",category:"Shared memory",prompt:"Which small moment would your partner save from the last month?",options:["A good meal","A quiet morning","A laugh with friends","An unexpected plan"]},
  {id:"rb-memory-02",module:"MEMORY",category:"Shared memory",prompt:"Pick the detail your partner noticed first on a recent date.",options:["The place","The music","The food","The conversation"]},
  {id:"rb-final-01",module:"FINAL DEFUSE",category:"Final defuse",prompt:"Choose the wire that represents the thing your partner ranked highest.",options:["Rest","Novelty","Good food"],answer:"Good food"},
  {id:"rb-final-02",module:"FINAL DEFUSE",category:"Final defuse",prompt:"Choose the final signal you both want to carry forward.",options:["Calm","Adventure","Laughter"],answer:"Laughter"},
];


