"use client";
import { useEffect, useMemo, useRef, useState, type PointerEvent } from "react";
import { ArrowDown, ArrowUp, Check, Clock3, Eraser, Pencil, Sparkles } from "lucide-react";
import { Button, Card } from "@/components/ui";
import { usePrivateInputs, type PrivateInput } from "../shared/use-private-inputs";
import type { GameViewProps } from "../shared/types";
import { rankSets } from "../moral-sync/content";

type Point={x:number;y:number};type Mark={color:string;points:Point[]};
const palette=["#69516b","#c75e76","#e59c4f","#398a78","#3878b8","#252a28"];
export function RankDrawSetup({session,command,busy}:Pick<GameViewProps,"session"|"command"|"busy">){
 const [count,setCount]=useState(Number(session.state.config_count||6));const [duration,setDuration]=useState(Number(session.state.duration??60));
 return <div className="rank-setup"><span className="eyebrow">A little insight, a little imagination</span><h2>Put your worlds in order</h2><p>Rank a few things, then turn a favourite into a drawing to guess.</p><div className="setup-control"><span>Rounds</span><div className="segmented-control">{[3,6,10].map(n=><button key={n} className={count===n?"selected":""} aria-pressed={count===n} onClick={()=>setCount(n)}>{n}</button>)}</div></div><div className="setup-control"><span>Drawing time</span><div className="segmented-control">{[[60,"60 sec"],[0,"No timer"]].map(([n,label])=><button key={String(n)} className={duration===Number(n)?"selected":""} aria-pressed={duration===Number(n)} onClick={()=>setDuration(Number(n))}>{label}</button>)}</div></div><Button secondary disabled={busy} onClick={()=>void command("configure",{count,duration:duration===0?"none":"timed"})}><Check size={16}/> Save game settings</Button></div>;
}
export function RankAndDraw({session,players,userId,command,busy,replay}:GameViewProps&{replay:()=>void}){
 const {inputs,error}=usePrivateInputs(session);const [ranking,setRanking]=useState<string[]>([]);const [guess,setGuess]=useState("");const [vote,setVote]=useState("");const [description,setDescription]=useState("");const [marks,setMarks]=useState<Mark[]>([]);const [current,setCurrent]=useState<Point[]>([]);const [color,setColor]=useState(palette[0]);const [erase,setErase]=useState(false);const [remaining,setRemaining]=useState(60);const surface=useRef<SVGSVGElement>(null);const drag=useRef<number|null>(null);
 const set=rankSets.find(x=>x.id===session.question_ids[session.round])||rankSets[session.round%rankSets.length];const phase=String(session.state.phase||"rank");const mine=(kind:string)=>inputs.find(x=>x.round===session.round&&x.kind===kind&&x.user_id===userId);const rows=(kind:string)=>inputs.filter(x=>x.round===session.round&&x.kind===kind);const myRank=mine("ranking");const partner=players.find(p=>p.user_id!==userId);const creator=String(session.state.creator_id||"");const isCreator=creator===userId;const special=session.state.special_round===true;const myDrawing=mine("drawing");const drawings=rows("drawing");const target=mine("target")?.value.item;
 const rounds=inputs.filter(x=>x.kind==="ranking"&&x.revealed);const topMatches=useMemo(()=>{const sum=rounds.filter(x=>{const pair=rounds.filter(y=>y.round===x.round);return pair.length===2&&pair[0].value.rank?.[0]===pair[1].value.rank?.[0]});return new Set(sum.map(x=>x.round)).size},[rounds]);
 useEffect(()=>{setRanking(set.items);setGuess("");setVote("");setDescription("");setMarks([]);setCurrent([])},[set.id]);
 useEffect(()=>{if(!session.state.ends_at)return;const interval=window.setInterval(()=>{const n=Math.max(0,Math.ceil((Date.parse(String(session.state.ends_at))-Date.now())/1000));setRemaining(n);if(n===0&&phase==="create"&&!busy&&(isCreator||special))void command("draw_finish")},500);return()=>clearInterval(interval)},[session.state.ends_at,phase,busy,command,isCreator,special]);
 useEffect(()=>{const stored=myDrawing?.value.marks;if(Array.isArray(stored))setMarks(stored as Mark[]);setDescription(String(myDrawing?.value.text||""))},[myDrawing?.created_at,session.round]);
 function reordered(from:number,to:number){setRanking(old=>{const a=[...old];if(to<0||to>=a.length)return old;[a[from],a[to]]=[a[to],a[from]];return a})}
 function point(e:PointerEvent<SVGSVGElement>):Point{const b=e.currentTarget.getBoundingClientRect();return{x:Math.max(0,Math.min(1000,(e.clientX-b.left)/b.width*1000)),y:Math.max(0,Math.min(600,(e.clientY-b.top)/b.height*600))}}
 function finishMark(e?:PointerEvent<SVGSVGElement>){if(e&&e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);if(!current.length)return;const next=[...marks,{color:erase?"#fffdf9":color,points:current}];setMarks(next);setCurrent([]);void command("draw_save",{marks:next})}
 function move(e:PointerEvent<SVGSVGElement>){if(!current.length)return;setCurrent(old=>[...old,point(e)])}
 const promptMode=(set.mode||(session.round%2===0?"draw":"describe"));const describeMode=promptMode==="describe"&&!special;const elapsed=Number(session.state.duration??60)>0;
 const sharedByRound=(kind:string,r:number)=>inputs.filter(x=>x.kind===kind&&x.round===r&&x.revealed);
 if(session.status==="finished")return <Card className="rank-results"><span className="eyebrow">RANK & DRAW</span><h2>Your vision, side by side</h2><p>A playful glimpse at where your instincts meet.</p><div className="rank-result-stats"><div><strong>{Math.round(rounds.length?topMatches/Math.max(1,new Set(rounds.map(x=>x.round)).size)*100:0)}%</strong><span>same top choice</span></div><div><strong>{Number(session.state.correct_guesses||0)}</strong><span>draws guessed</span></div><div><strong>{topMatches}</strong><span>perfect first picks</span></div></div><h3>Your gallery</h3><div className="rank-gallery">{Array.from({length:session.total_rounds},(_,r)=>{const d=sharedByRound("drawing",r);return <Card key={r}><strong>{rankSets.find(x=>x.id===session.question_ids[r])?.title}</strong><div className="gallery-drawings">{d.map(x=>x.value.text?<p key={x.user_id}>{String(x.value.text)}</p>:<svg key={x.user_id} viewBox="0 0 1000 600">{((x.value.marks||[]) as Mark[]).map((m,i)=><polyline key={i} points={m.points.map(p=>`${p.x},${p.y}`).join(" ")} fill="none" stroke={m.color} strokeWidth="8" strokeLinecap="round" strokeLinejoin="round"/>)}</svg>)}</div></Card>})}</div><Button disabled={busy} onClick={replay}>Play again</Button></Card>;
 return <div className="rank-game"><div className="rank-game-top"><div><span className="eyebrow">ROUND {session.round+1} OF {session.total_rounds}</span><h2>{phase==="rank"?"Rank it your way":set.title}</h2></div><div className="rank-progress">{phase.toUpperCase()}<progress value={session.round+1} max={session.total_rounds}/></div></div>
 {phase==="rank"&&<><Card className="rank-prompt"><span className="eyebrow">{set.category.toUpperCase()}</span><h3>{set.title}</h3><p>Drag to reorder, or use the arrows to move a choice.</p></Card><ol className="ranking-list">{ranking.map((item,index)=><li key={item} draggable={!myRank&&!busy} onDragStart={()=>{drag.current=index}} onDragOver={e=>e.preventDefault()} onDrop={()=>{if(drag.current!==null)reordered(drag.current,index)}}><span className="rank-index">{index+1}</span><strong>{item}</strong><div><button disabled={!!myRank||busy||index===0} onClick={()=>reordered(index,index-1)} aria-label={`Move ${item} up`}><ArrowUp size={17}/></button><button disabled={!!myRank||busy||index===ranking.length-1} onClick={()=>reordered(index,index+1)} aria-label={`Move ${item} down`}><ArrowDown size={17}/></button></div></li>)}</ol><Button disabled={!!myRank||busy||ranking.length!==5} onClick={()=>void command("lock",{rank:ranking})}><Check size={16}/>{myRank?"Ranking locked":"Lock my ranking"}</Button>{myRank&&<p className="field-note">Your order is saved privately. Waiting for {partner?.name}…</p>}</>}
 {phase==="reveal"&&<><Card className="rank-reveal"><span className="eyebrow">SAME SET · TWO DIFFERENT ORDERS</span><h2>A little same, a little different</h2><div className="rank-pairs">{players.map(p=>{const row=rows("ranking").find(x=>x.user_id===p.user_id);const list=(row?.value.rank||[]) as string[];return <div key={p.user_id}><h3>{p.user_id===userId?"YOU":p.name.toUpperCase()}</h3>{list.map((item,i)=><p key={item}><span>{i+1}</span>{item}</p>)}</div>})}</div><p className="rank-diff">{rankSets.length&&"Different rankings are part of the fun."}</p><Button disabled={busy||!!mine("next")} onClick={()=>void command("continue")}>Make something from it <Sparkles size={16}/></Button><p className="field-note">The next phase opens when you’re both ready.</p></Card></>}
 {phase==="create"&&<><div className="create-instruction"><span className="eyebrow">{special?"DRAW YOUR VERSION":"CREATIVE ROUND"}</span><h2>{special?`Draw ${set.title.toLowerCase()} together`:describeMode?"Describe it, partner guesses":`${isCreator?"Draw":"Watch the canvas"}, partner guesses`}</h2><p>{special?"Both draw the same idea. No wrong interpretation.":isCreator?`Secret idea: ${String(target||set.items[0])}. ${describeMode?"Describe it without naming it.":"Draw it for your partner."}`:`Try to guess what ${partner?.name} is showing you.`}</p></div>
   {special||isCreator&&!describeMode?<><div className="canvas-toolbar"><div className="color-palette">{palette.map(c=><button key={c} className={color===c&&!erase?"active":""} style={{background:c}} aria-label={`Use ${c} pen`} onClick={()=>{setColor(c);setErase(false)}}/></div><button className={`tool-button ${erase?"active":""}`} aria-label="Eraser" onClick={()=>setErase(v=>!v)}><Eraser size={18}/></button><button className="tool-button" aria-label="Undo last mark" onClick={()=>{const next=marks.slice(0,-1);setMarks(next);void command("draw_save",{marks:next})}}><span>↶</span></button>{elapsed&&<span className="canvas-timer"><Clock3 size={15}/>{remaining}s</span>}</div><svg ref={surface} className="rank-canvas" viewBox="0 0 1000 600" role="img" aria-label="Draw here with touch or mouse" onPointerDown={e=>{if(!e.isPrimary||myDrawing?.revealed)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);setCurrent([point(e)])}} onPointerMove={move} onPointerUp={finishMark} onPointerCancel={finishMark}><rect width="1000" height="600" rx="22" fill="#fffdf9"/><g pointerEvents="none">{marks.map((m,i)=><polyline key={i} points={m.points.map(p=>`${p.x},${p.y}`).join(" ")} fill="none" stroke={m.color} strokeWidth="10" strokeLinecap="round" strokeLinejoin="round"/>)}{current.length>0&&<polyline points={current.map(p=>`${p.x},${p.y}`).join(" ")} fill="none" stroke={erase?"#fffdf9":color} strokeWidth="10" strokeLinecap="round" strokeLinejoin="round"/>}</g></svg><Button disabled={busy||!!myDrawing?.revealed} onClick={()=>void command("draw_finish")}>{myDrawing?.revealed?"Your drawing is ready":"Finish drawing"}</Button></>:isCreator&&describeMode?<div className="describe-card"><p>Describe your idea without saying its name.</p><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Describe it in a few words" maxLength={220}/><Button disabled={busy||!!myDrawing?.revealed} onClick={async()=>{if(!await command("draw_save",{text:description}))return;void command("draw_finish")}}>Lock description</Button></div>:<Card><span className="field-note">Your partner is creating a clue. It will appear when it’s ready.</span></Card>}
   </>}
 {phase==="guess"&&<Card className="guess-card"><span className="eyebrow">WHAT DID THEY HAVE IN MIND?</span><h2>Which one was your partner drawing?</h2>{drawings.map(d=>d.value.text?<blockquote key={d.user_id}>{String(d.value.text)}</blockquote>:<svg key={d.user_id} viewBox="0 0 1000 600" className="guess-canvas">{((d.value.marks||[]) as Mark[]).map((m,i)=><polyline key={i} points={m.points.map(p=>`${p.x},${p.y}`).join(" ")} fill="none" stroke={m.color} strokeWidth="10" strokeLinecap="round" strokeLinejoin="round"/>)}</svg>)}<div className="guess-options">{set.items.map(x=><button key={x} className={guess===x?"selected":""} disabled={!!mine("guess")} onClick={()=>setGuess(x)}>{x}</button>)}</div><Button disabled={!guess||busy||!!mine("guess")} onClick={()=>void command("guess",{item:guess})}>{mine("guess")?"Guess locked":"Lock guess"}</Button></Card>}
 {phase==="vote"&&<Card className="vote-card"><span className="eyebrow">TWO SKETCHES · ONE SHARED IDEA</span><h2>Whose place are we moving into?</h2><div className="rank-pairs">{drawings.map(d=><div key={d.user_id}><h3>{players.find(p=>p.user_id===d.user_id)?.name}</h3><svg viewBox="0 0 1000 600" className="guess-canvas">{((d.value.marks||[]) as Mark[]).map((m,i)=><polyline key={i} points={m.points.map(p=>`${p.x},${p.y}`).join(" ")} fill="none" stroke={m.color} strokeWidth="10" strokeLinecap="round" strokeLinejoin="round"/>)}</svg></div>)}</div><div className="guess-options">{[["mine","Mine"],["yours","Yours"],["mix","Mix both"]].map(([id,label])=><button key={id} className={vote===id?"selected":""} onClick={()=>setVote(id)} disabled={!!mine("vote")}>{label}</button>)}</div><Button disabled={!vote||busy||!!mine("vote")} onClick={()=>void command("vote",{vote})}>{mine("vote")?"Vote saved privately":"Lock my vote"}</Button></Card>}
 {phase==="compare"&&<Card className="rank-compare"><span className="eyebrow">{special?"OUR VERSION":"THE REVEAL"}</span><h2>{special?"Both of you imagined it":"Was that the idea?"}</h2><p>{special?"The best version might be both.":`Your guess: ${String(session.state.last_guess||"—")}`}</p>{drawings.map(d=>d.value.text?<blockquote key={d.user_id}>{String(d.value.text)}</blockquote>:<svg key={d.user_id} viewBox="0 0 1000 600" className="guess-canvas">{((d.value.marks||[]) as Mark[]).map((m,i)=><polyline key={i} points={m.points.map(p=>`${p.x},${p.y}`).join(" ")} fill="none" stroke={m.color} strokeWidth="10" strokeLinecap="round" strokeLinejoin="round"/>)}</svg>)}<Button disabled={busy||!!mine("next")} onClick={()=>void command("continue")}>Next round <ArrowRight size={16}/></Button></Card>}
 {error&&<p className="notice" role="status">{error}</p>}
 </div>;
}

