-- Generated from src/games/shared/content.ts. Keep seeds and typed content in sync.
insert into public.game_content(id,game,category,prompt,option_a,option_b) values
('this-or-that-travel-1','this-or-that','Travel','This or that?','Mountains','Beach'),
('this-or-that-travel-2','this-or-that','Travel','This or that?','City break','Countryside escape'),
('this-or-that-travel-3','this-or-that','Travel','This or that?','Road trip','Train journey'),
('this-or-that-travel-4','this-or-that','Travel','This or that?','One long holiday','Several short trips'),
('this-or-that-travel-5','this-or-that','Travel','This or that?','Museum afternoon','Local market morning'),
('this-or-that-travel-6','this-or-that','Travel','This or that?','Snowy cabin','Seaside cottage'),
('this-or-that-travel-7','this-or-that','Travel','This or that?','Travel with a plan','Follow your curiosity'),
('this-or-that-travel-8','this-or-that','Travel','This or that?','Return to a favorite place','Go somewhere new'),
('this-or-that-travel-9','this-or-that','Travel','This or that?','Sunrise hike','Midnight walk'),
('this-or-that-travel-10','this-or-that','Travel','This or that?','Camping','Boutique hotel'),
('this-or-that-lifestyle-1','this-or-that','Lifestyle','This or that?','Early mornings','Late nights'),
('this-or-that-lifestyle-2','this-or-that','Lifestyle','This or that?','A full calendar','An open weekend'),
('this-or-that-lifestyle-3','this-or-that','Lifestyle','This or that?','Cook together','Order takeaway'),
('this-or-that-lifestyle-4','this-or-that','Lifestyle','This or that?','Live abroad','Stay close to home'),
('this-or-that-lifestyle-5','this-or-that','Lifestyle','This or that?','Minimalist home','Home full of keepsakes'),
('this-or-that-lifestyle-6','this-or-that','Lifestyle','This or that?','A busy city','A quiet village'),
('this-or-that-lifestyle-7','this-or-that','Lifestyle','This or that?','Phone call','Voice message'),
('this-or-that-lifestyle-8','this-or-that','Lifestyle','This or that?','Finish one book','Read several at once'),
('this-or-that-lifestyle-9','this-or-that','Lifestyle','This or that?','A tidy desk','Creative chaos'),
('this-or-that-lifestyle-10','this-or-that','Lifestyle','This or that?','Save for a big experience','Enjoy small treats often'),
('this-or-that-food-1','this-or-that','Food','This or that?','Sweet breakfast','Savory breakfast'),
('this-or-that-food-2','this-or-that','Food','This or that?','Pizza night','Sushi night'),
('this-or-that-food-3','this-or-that','Food','This or that?','Coffee','Tea'),
('this-or-that-food-4','this-or-that','Food','This or that?','Try a new restaurant','Return to a favorite'),
('this-or-that-food-5','this-or-that','Food','This or that?','Chocolate dessert','Fruit dessert'),
('this-or-that-food-6','this-or-that','Food','This or that?','Spicy food','Mild food'),
('this-or-that-food-7','this-or-that','Food','This or that?','Picnic','Candlelit dinner'),
('this-or-that-food-8','this-or-that','Food','This or that?','Pasta','Tacos'),
('this-or-that-food-9','this-or-that','Food','This or that?','Bake something','Cook something'),
('this-or-that-food-10','this-or-that','Food','This or that?','Share one dessert','Choose your own'),
('this-or-that-us-1','this-or-that','Us','This or that?','A thoughtful note','A surprise outing'),
('this-or-that-us-2','this-or-that','Us','This or that?','Stay in','Go out'),
('this-or-that-us-3','this-or-that','Us','This or that?','Dance together','Sing together'),
('this-or-that-us-4','this-or-that','Us','This or that?','A long hug','Holding hands'),
('this-or-that-us-5','this-or-that','Us','This or that?','Plan a date','Be surprised'),
('this-or-that-us-6','this-or-that','Us','This or that?','Matching hobbies','Different interests'),
('this-or-that-us-7','this-or-that','Us','This or that?','Take photos','Stay in the moment'),
('this-or-that-us-8','this-or-that','Us','This or that?','Big celebration','Quiet celebration'),
('this-or-that-us-9','this-or-that','Us','This or that?','Breakfast date','Evening date'),
('this-or-that-us-10','this-or-that','Us','This or that?','Revisit our first date','Invent a new tradition'),
('this-or-that-future-1','this-or-that','Future','This or that?','A garden','A rooftop terrace'),
('this-or-that-future-2','this-or-that','Future','This or that?','Learn a language','Learn an instrument'),
('this-or-that-future-3','this-or-that','Future','This or that?','Build something','Grow something'),
('this-or-that-future-4','this-or-that','Future','This or that?','A year of travel','A year creating a home'),
('this-or-that-future-5','this-or-that','Future','This or that?','Adopt a dog','Adopt a cat'),
('this-or-that-future-6','this-or-that','Future','This or that?','A home library','A home cinema'),
('this-or-that-future-7','this-or-that','Future','This or that?','Work from anywhere','Have a dedicated studio'),
('this-or-that-future-8','this-or-that','Future','This or that?','Learn to sail','Learn to ski'),
('this-or-that-future-9','this-or-that','Future','This or that?','Host friends often','Meet friends out'),
('this-or-that-future-10','this-or-that','Future','This or that?','A tiny house','An old house to restore'),
('this-or-that-funny-1','this-or-that','Funny','This or that?','Talk to animals','Speak every language'),
('this-or-that-funny-2','this-or-that','Funny','This or that?','Teleport','Fly'),
('this-or-that-funny-3','this-or-that','Funny','This or that?','Always find lost things','Always pick the right queue'),
('this-or-that-funny-4','this-or-that','Funny','This or that?','A personal chef','A personal driver'),
('this-or-that-funny-5','this-or-that','Funny','This or that?','Win a quiz show','Win a dance contest'),
('this-or-that-funny-6','this-or-that','Funny','This or that?','Only whisper','Only sing'),
('this-or-that-funny-7','this-or-that','Funny','This or that?','Be in a musical','Be in a mystery'),
('this-or-that-funny-8','this-or-that','Funny','This or that?','Swap playlists','Swap wardrobes'),
('this-or-that-funny-9','this-or-that','Funny','This or that?','Know every movie ending','Never remember spoilers'),
('this-or-that-funny-10','this-or-that','Funny','This or that?','A week without mirrors','A week without clocks'),
('do-you-know-me-easy-1','do-you-know-me','Easy','What is my comfort food?',null,null),
('do-you-know-me-easy-2','do-you-know-me','Easy','What would my ideal Sunday look like?',null,null),
('do-you-know-me-easy-3','do-you-know-me','Easy','Which season do I enjoy most?',null,null),
('do-you-know-me-easy-4','do-you-know-me','Easy','What drink do I usually order?',null,null),
('do-you-know-me-easy-5','do-you-know-me','Easy','Which film could I watch again and again?',null,null),
('do-you-know-me-easy-6','do-you-know-me','Easy','What is my favorite way to exercise?',null,null),
('do-you-know-me-easy-7','do-you-know-me','Easy','Am I most energetic in the morning or evening?',null,null),
('do-you-know-me-easy-8','do-you-know-me','Easy','What is my favorite holiday destination so far?',null,null),
('do-you-know-me-easy-9','do-you-know-me','Easy','Which snack would I pick on a road trip?',null,null),
('do-you-know-me-easy-10','do-you-know-me','Easy','What kind of weather makes me happiest?',null,null),
('do-you-know-me-easy-11','do-you-know-me','Easy','What is my favorite room at home?',null,null),
('do-you-know-me-easy-12','do-you-know-me','Easy','Which music do I put on to relax?',null,null),
('do-you-know-me-easy-13','do-you-know-me','Easy','What breakfast would I choose today?',null,null),
('do-you-know-me-personal-1','do-you-know-me','Personal','What usually cheers me up after a difficult day?',null,null),
('do-you-know-me-personal-2','do-you-know-me','Personal','What achievement am I proud of?',null,null),
('do-you-know-me-personal-3','do-you-know-me','Personal','What is a skill I want to improve?',null,null),
('do-you-know-me-personal-4','do-you-know-me','Personal','What makes me feel appreciated?',null,null),
('do-you-know-me-personal-5','do-you-know-me','Personal','What helps me feel calm?',null,null),
('do-you-know-me-personal-6','do-you-know-me','Personal','What quality do I value most in a friend?',null,null),
('do-you-know-me-personal-7','do-you-know-me','Personal','What do I find hardest to ask for?',null,null),
('do-you-know-me-personal-8','do-you-know-me','Personal','What small thing makes me laugh?',null,null),
('do-you-know-me-personal-9','do-you-know-me','Personal','What is a habit I am trying to build?',null,null),
('do-you-know-me-personal-10','do-you-know-me','Personal','When do I feel most confident?',null,null),
('do-you-know-me-personal-11','do-you-know-me','Personal','What is something I tend to overthink?',null,null),
('do-you-know-me-personal-12','do-you-know-me','Personal','What kind of compliment means most to me?',null,null),
('do-you-know-me-personal-13','do-you-know-me','Personal','How do I prefer to spend time alone?',null,null),
('do-you-know-me-future-1','do-you-know-me','Future','Where would I love to live for a year?',null,null),
('do-you-know-me-future-2','do-you-know-me','Future','Which place is still on my travel list?',null,null),
('do-you-know-me-future-3','do-you-know-me','Future','What would I like to learn next?',null,null),
('do-you-know-me-future-4','do-you-know-me','Future','What would my dream home include?',null,null),
('do-you-know-me-future-5','do-you-know-me','Future','Which adventure would I choose for us?',null,null),
('do-you-know-me-future-6','do-you-know-me','Future','What would I do with a free month?',null,null),
('do-you-know-me-future-7','do-you-know-me','Future','What personal goal matters to me this year?',null,null),
('do-you-know-me-future-8','do-you-know-me','Future','What would I love to create?',null,null),
('do-you-know-me-future-9','do-you-know-me','Future','What tradition would I like us to start?',null,null),
('do-you-know-me-future-10','do-you-know-me','Future','Which job would I try for a day?',null,null),
('do-you-know-me-future-11','do-you-know-me','Future','What would I want more time for?',null,null),
('do-you-know-me-future-12','do-you-know-me','Future','What do I picture on an ideal birthday?',null,null),
('do-you-know-me-funny-1','do-you-know-me','Funny','What would I spend a surprise €1,000 on first?',null,null),
('do-you-know-me-funny-2','do-you-know-me','Funny','What is my most useless talent?',null,null),
('do-you-know-me-funny-3','do-you-know-me','Funny','Which reality show would I last longest on?',null,null),
('do-you-know-me-funny-4','do-you-know-me','Funny','What animal best matches my personality?',null,null),
('do-you-know-me-funny-5','do-you-know-me','Funny','What would my karaoke song be?',null,null),
('do-you-know-me-funny-6','do-you-know-me','Funny','What would I name a boat?',null,null),
('do-you-know-me-funny-7','do-you-know-me','Funny','Which fictional world would I visit?',null,null),
('do-you-know-me-funny-8','do-you-know-me','Funny','What household task do I avoid most?',null,null),
('do-you-know-me-funny-9','do-you-know-me','Funny','What would I accidentally become famous for?',null,null),
('do-you-know-me-funny-10','do-you-know-me','Funny','What ridiculous invention would I buy?',null,null),
('do-you-know-me-funny-11','do-you-know-me','Funny','What would I pack first for a desert island?',null,null),
('do-you-know-me-funny-12','do-you-know-me','Funny','Which food could I eat for a whole week?',null,null),
('deep-talk-us-1','deep-talk','Us','What is something you hope we never stop doing together?',null,null),
('deep-talk-us-2','deep-talk','Us','When do you feel most understood by me?',null,null),
('deep-talk-us-3','deep-talk','Us','Which ordinary moment with us would you keep?',null,null),
('deep-talk-us-4','deep-talk','Us','What has surprised you about our relationship?',null,null),
('deep-talk-us-5','deep-talk','Us','What does quality time mean to you lately?',null,null),
('deep-talk-us-6','deep-talk','Us','What is one way we make a good team?',null,null),
('deep-talk-us-7','deep-talk','Us','What would you like us to celebrate more often?',null,null),
('deep-talk-us-8','deep-talk','Us','Which small ritual feels like ours?',null,null),
('deep-talk-us-9','deep-talk','Us','What have we taught each other?',null,null),
('deep-talk-us-10','deep-talk','Us','What would make our next month together special?',null,null),
('deep-talk-future-1','deep-talk','Future','What would you like our life to feel like in five years?',null,null),
('deep-talk-future-2','deep-talk','Future','What matters more to you now than it did five years ago?',null,null),
('deep-talk-future-3','deep-talk','Future','What kind of home do you want to build emotionally?',null,null),
('deep-talk-future-4','deep-talk','Future','Which adventure should we stop postponing?',null,null),
('deep-talk-future-5','deep-talk','Future','What would a slower life look like for us?',null,null),
('deep-talk-future-6','deep-talk','Future','What do you want to make room for next year?',null,null),
('deep-talk-future-7','deep-talk','Future','Which future decision are you curious about?',null,null),
('deep-talk-future-8','deep-talk','Future','What would you like to learn together?',null,null),
('deep-talk-future-9','deep-talk','Future','What should remain the same as our lives change?',null,null),
('deep-talk-future-10','deep-talk','Future','What would you do if you had one completely free year?',null,null),
('deep-talk-dreams-1','deep-talk','Dreams','What dream have you kept mostly to yourself?',null,null),
('deep-talk-dreams-2','deep-talk','Dreams','What did you want to become before you knew what jobs paid?',null,null),
('deep-talk-dreams-3','deep-talk','Dreams','What would you create if nobody judged it?',null,null),
('deep-talk-dreams-4','deep-talk','Dreams','Which place lives in your imagination?',null,null),
('deep-talk-dreams-5','deep-talk','Dreams','What would your perfect ordinary day include?',null,null),
('deep-talk-dreams-6','deep-talk','Dreams','What would you attempt with a little more courage?',null,null),
('deep-talk-dreams-7','deep-talk','Dreams','What is a dream you have outgrown?',null,null),
('deep-talk-dreams-8','deep-talk','Dreams','Who inspires you to imagine more for yourself?',null,null),
('deep-talk-dreams-9','deep-talk','Dreams','What is a small dream we could make happen soon?',null,null),
('deep-talk-dreams-10','deep-talk','Dreams','What does success look like without an audience?',null,null),
('deep-talk-childhood-1','deep-talk','Childhood','Which childhood place can you still picture clearly?',null,null),
('deep-talk-childhood-2','deep-talk','Childhood','What made you feel safe as a child?',null,null),
('deep-talk-childhood-3','deep-talk','Childhood','What game could you play for hours?',null,null),
('deep-talk-childhood-4','deep-talk','Childhood','Which family saying has stayed with you?',null,null),
('deep-talk-childhood-5','deep-talk','Childhood','What did you love doing after school?',null,null),
('deep-talk-childhood-6','deep-talk','Childhood','Who noticed something special in you early on?',null,null),
('deep-talk-childhood-7','deep-talk','Childhood','What did your childhood bedroom look like?',null,null),
('deep-talk-childhood-8','deep-talk','Childhood','What food brings back a childhood memory?',null,null),
('deep-talk-childhood-9','deep-talk','Childhood','What did you misunderstand about adults?',null,null),
('deep-talk-childhood-10','deep-talk','Childhood','What would younger you be delighted by now?',null,null),
('deep-talk-memories-1','deep-talk','Memories','Which day would you like to relive for an hour?',null,null),
('deep-talk-memories-2','deep-talk','Memories','What is a smell that takes you somewhere else?',null,null),
('deep-talk-memories-3','deep-talk','Memories','Which trip changed your perspective?',null,null),
('deep-talk-memories-4','deep-talk','Memories','What is a kindness you still remember?',null,null),
('deep-talk-memories-5','deep-talk','Memories','Which photo means more than it looks like?',null,null),
('deep-talk-memories-6','deep-talk','Memories','What is a favorite memory of laughing together?',null,null),
('deep-talk-memories-7','deep-talk','Memories','What ordinary day became unexpectedly important?',null,null),
('deep-talk-memories-8','deep-talk','Memories','Which song belongs to a particular time in your life?',null,null),
('deep-talk-memories-9','deep-talk','Memories','What is a moment you wish you had photographed?',null,null),
('deep-talk-memories-10','deep-talk','Memories','What is one memory you would like to tell me in more detail?',null,null),
('deep-talk-funny-1','deep-talk','Funny','What would our extremely low-budget TV show be called?',null,null),
('deep-talk-funny-2','deep-talk','Funny','Which harmless rule would you invent for the world?',null,null),
('deep-talk-funny-3','deep-talk','Funny','What would we be terrible at as a team?',null,null),
('deep-talk-funny-4','deep-talk','Funny','What is the strangest thing you believed confidently?',null,null),
('deep-talk-funny-5','deep-talk','Funny','What would your autobiography title be this week?',null,null),
('deep-talk-funny-6','deep-talk','Funny','Which fictional character would be a terrible housemate?',null,null),
('deep-talk-funny-7','deep-talk','Funny','What is a tiny inconvenience you take too seriously?',null,null),
('deep-talk-funny-8','deep-talk','Funny','If our pet could review us, what would it say?',null,null),
('deep-talk-funny-9','deep-talk','Funny','What would you put in a museum of your life?',null,null),
('deep-talk-funny-10','deep-talk','Funny','What is a very specific talent you wish existed?',null,null),
('deep-talk-vulnerable-1','deep-talk','Vulnerable','What helps you feel comfortable being honest?',null,null),
('deep-talk-vulnerable-2','deep-talk','Vulnerable','What is something you are learning to accept about yourself?',null,null),
('deep-talk-vulnerable-3','deep-talk','Vulnerable','How can I support you when you feel overwhelmed?',null,null),
('deep-talk-vulnerable-4','deep-talk','Vulnerable','What does a sincere apology look like to you?',null,null),
('deep-talk-vulnerable-5','deep-talk','Vulnerable','When do you need listening rather than advice?',null,null),
('deep-talk-vulnerable-6','deep-talk','Vulnerable','What expectation would you like to let go of?',null,null),
('deep-talk-vulnerable-7','deep-talk','Vulnerable','What is something you find easier to write than say?',null,null),
('deep-talk-vulnerable-8','deep-talk','Vulnerable','What boundary helps you feel more present?',null,null),
('deep-talk-vulnerable-9','deep-talk','Vulnerable','What would you like to give yourself permission to do?',null,null),
('deep-talk-vulnerable-10','deep-talk','Vulnerable','What does feeling emotionally safe mean to you?',null,null),
('deep-talk-random-1','deep-talk','Random','What have you changed your mind about in recent years?',null,null),
('deep-talk-random-2','deep-talk','Random','What do you wish people asked you about more?',null,null),
('deep-talk-random-3','deep-talk','Random','Which small luxury improves your life most?',null,null),
('deep-talk-random-4','deep-talk','Random','What skill do you admire in other people?',null,null),
('deep-talk-random-5','deep-talk','Random','What is worth doing slowly?',null,null),
('deep-talk-random-6','deep-talk','Random','What kind of beauty do you notice first?',null,null),
('deep-talk-random-7','deep-talk','Random','What makes a place feel like home?',null,null),
('deep-talk-random-8','deep-talk','Random','What has been taking up your thoughts lately?',null,null),
('deep-talk-random-9','deep-talk','Random','What would you like to understand better?',null,null),
('deep-talk-random-10','deep-talk','Random','What are you grateful you no longer worry about?',null,null),
('drawing-word-objects-1','drawing-word','Objects','Umbrella',null,null),
('drawing-word-objects-2','drawing-word','Objects','Bicycle',null,null),
('drawing-word-objects-3','drawing-word','Objects','Camera',null,null),
('drawing-word-objects-4','drawing-word','Objects','Candle',null,null),
('drawing-word-objects-5','drawing-word','Objects','Backpack',null,null),
('drawing-word-objects-6','drawing-word','Objects','Clock',null,null),
('drawing-word-objects-7','drawing-word','Objects','Key',null,null),
('drawing-word-objects-8','drawing-word','Objects','Glasses',null,null),
('drawing-word-objects-9','drawing-word','Objects','Headphones',null,null),
('drawing-word-objects-10','drawing-word','Objects','Scissors',null,null),
('drawing-word-objects-11','drawing-word','Objects','Ladder',null,null),
('drawing-word-objects-12','drawing-word','Objects','Balloon',null,null),
('drawing-word-objects-13','drawing-word','Objects','Guitar',null,null),
('drawing-word-objects-14','drawing-word','Objects','Teapot',null,null),
('drawing-word-objects-15','drawing-word','Objects','Suitcase',null,null),
('drawing-word-objects-16','drawing-word','Objects','Toothbrush',null,null),
('drawing-word-objects-17','drawing-word','Objects','Telescope',null,null),
('drawing-word-objects-18','drawing-word','Objects','Book',null,null),
('drawing-word-objects-19','drawing-word','Objects','Lamp',null,null),
('drawing-word-objects-20','drawing-word','Objects','Kite',null,null),
('drawing-word-animals-1','drawing-word','Animals','Elephant',null,null),
('drawing-word-animals-2','drawing-word','Animals','Penguin',null,null),
('drawing-word-animals-3','drawing-word','Animals','Giraffe',null,null),
('drawing-word-animals-4','drawing-word','Animals','Turtle',null,null),
('drawing-word-animals-5','drawing-word','Animals','Butterfly',null,null),
('drawing-word-animals-6','drawing-word','Animals','Octopus',null,null),
('drawing-word-animals-7','drawing-word','Animals','Rabbit',null,null),
('drawing-word-animals-8','drawing-word','Animals','Flamingo',null,null),
('drawing-word-animals-9','drawing-word','Animals','Hedgehog',null,null),
('drawing-word-animals-10','drawing-word','Animals','Dolphin',null,null),
('drawing-word-animals-11','drawing-word','Animals','Owl',null,null),
('drawing-word-animals-12','drawing-word','Animals','Snail',null,null),
('drawing-word-animals-13','drawing-word','Animals','Crab',null,null),
('drawing-word-animals-14','drawing-word','Animals','Frog',null,null),
('drawing-word-animals-15','drawing-word','Animals','Jellyfish',null,null),
('drawing-word-animals-16','drawing-word','Animals','Cat',null,null),
('drawing-word-animals-17','drawing-word','Animals','Dog',null,null),
('drawing-word-animals-18','drawing-word','Animals','Bee',null,null),
('drawing-word-animals-19','drawing-word','Animals','Shark',null,null),
('drawing-word-animals-20','drawing-word','Animals','Peacock',null,null),
('drawing-word-food-1','drawing-word','Food','Pizza',null,null),
('drawing-word-food-2','drawing-word','Food','Ice cream',null,null),
('drawing-word-food-3','drawing-word','Food','Watermelon',null,null),
('drawing-word-food-4','drawing-word','Food','Croissant',null,null),
('drawing-word-food-5','drawing-word','Food','Pancakes',null,null),
('drawing-word-food-6','drawing-word','Food','Popcorn',null,null),
('drawing-word-food-7','drawing-word','Food','Pineapple',null,null),
('drawing-word-food-8','drawing-word','Food','Taco',null,null),
('drawing-word-food-9','drawing-word','Food','Cupcake',null,null),
('drawing-word-food-10','drawing-word','Food','Banana',null,null),
('drawing-word-food-11','drawing-word','Food','Sushi',null,null),
('drawing-word-food-12','drawing-word','Food','Spaghetti',null,null),
('drawing-word-food-13','drawing-word','Food','Donut',null,null),
('drawing-word-food-14','drawing-word','Food','Carrot',null,null),
('drawing-word-food-15','drawing-word','Food','Strawberry',null,null),
('drawing-word-food-16','drawing-word','Food','Cheese',null,null),
('drawing-word-food-17','drawing-word','Food','Pretzel',null,null),
('drawing-word-food-18','drawing-word','Food','Avocado',null,null),
('drawing-word-food-19','drawing-word','Food','Sandwich',null,null),
('drawing-word-food-20','drawing-word','Food','Pear',null,null),
('drawing-word-places-1','drawing-word','Places','Lighthouse',null,null),
('drawing-word-places-2','drawing-word','Places','Castle',null,null),
('drawing-word-places-3','drawing-word','Places','Beach',null,null),
('drawing-word-places-4','drawing-word','Places','Volcano',null,null),
('drawing-word-places-5','drawing-word','Places','Bridge',null,null),
('drawing-word-places-6','drawing-word','Places','Treehouse',null,null),
('drawing-word-places-7','drawing-word','Places','Cinema',null,null),
('drawing-word-places-8','drawing-word','Places','Library',null,null),
('drawing-word-places-9','drawing-word','Places','Airport',null,null),
('drawing-word-places-10','drawing-word','Places','Farm',null,null),
('drawing-word-places-11','drawing-word','Places','Mountain',null,null),
('drawing-word-places-12','drawing-word','Places','Island',null,null),
('drawing-word-places-13','drawing-word','Places','Campsite',null,null),
('drawing-word-places-14','drawing-word','Places','Bakery',null,null),
('drawing-word-places-15','drawing-word','Places','Playground',null,null),
('drawing-word-places-16','drawing-word','Places','Train station',null,null),
('drawing-word-places-17','drawing-word','Places','Desert',null,null),
('drawing-word-places-18','drawing-word','Places','Waterfall',null,null),
('drawing-word-places-19','drawing-word','Places','Igloo',null,null),
('drawing-word-places-20','drawing-word','Places','Garden',null,null),
('drawing-word-random-1','drawing-word','Random','Rainbow',null,null),
('drawing-word-random-2','drawing-word','Random','Snowman',null,null),
('drawing-word-random-3','drawing-word','Random','Rocket',null,null),
('drawing-word-random-4','drawing-word','Random','Robot',null,null),
('drawing-word-random-5','drawing-word','Random','Mermaid',null,null),
('drawing-word-random-6','drawing-word','Random','Pirate',null,null),
('drawing-word-random-7','drawing-word','Random','Astronaut',null,null),
('drawing-word-random-8','drawing-word','Random','Treasure chest',null,null),
('drawing-word-random-9','drawing-word','Random','Hot air balloon',null,null),
('drawing-word-random-10','drawing-word','Random','Shooting star',null,null),
('drawing-word-random-11','drawing-word','Random','Campfire',null,null),
('drawing-word-random-12','drawing-word','Random','Snowflake',null,null),
('drawing-word-random-13','drawing-word','Random','Planet',null,null),
('drawing-word-random-14','drawing-word','Random','Ghost',null,null),
('drawing-word-random-15','drawing-word','Random','Crown',null,null),
('drawing-word-random-16','drawing-word','Random','Magic wand',null,null),
('drawing-word-random-17','drawing-word','Random','Love letter',null,null),
('drawing-word-random-18','drawing-word','Random','Roller coaster',null,null),
('drawing-word-random-19','drawing-word','Random','Dinosaur',null,null),
('drawing-word-random-20','drawing-word','Random','Compass',null,null),
('daily-us-connection-1','daily-us','Connection','What is one thing you look forward to doing together?',null,null),
('daily-us-connection-2','daily-us','Connection','What made you think of me today?',null,null),
('daily-us-connection-3','daily-us','Connection','What would make tonight feel special?',null,null),
('daily-us-connection-4','daily-us','Connection','What is one thing you appreciated about us this week?',null,null),
('daily-us-connection-5','daily-us','Connection','What should our next small adventure be?',null,null),
('daily-us-connection-6','daily-us','Connection','What would you like to tell me more about?',null,null),
('daily-us-connection-7','daily-us','Connection','What is one thing we do well together?',null,null),
('daily-us-connection-8','daily-us','Connection','What would you like us to make time for?',null,null),
('daily-us-connection-9','daily-us','Connection','What is your favorite way to say hello after a long day?',null,null),
('daily-us-connection-10','daily-us','Connection','What shared moment would you repeat?',null,null),
('daily-us-connection-11','daily-us','Connection','What made you smile about us recently?',null,null),
('daily-us-connection-12','daily-us','Connection','What is one thing you would like to ask me?',null,null),
('daily-us-connection-13','daily-us','Connection','Which song would you send me today?',null,null),
('daily-us-connection-14','daily-us','Connection','What would you put in a care package for me?',null,null),
('daily-us-connection-15','daily-us','Connection','What is a little tradition you would like to keep?',null,null),
('daily-us-connection-16','daily-us','Connection','What would our ideal lunch break together look like?',null,null),
('daily-us-connection-17','daily-us','Connection','What is something you want to thank me for?',null,null),
('daily-us-connection-18','daily-us','Connection','What would you like to discover about each other?',null,null),
('daily-us-connection-19','daily-us','Connection','What is one way we can make tomorrow easier?',null,null),
('daily-us-connection-20','daily-us','Connection','What feels especially good about being a team?',null,null),
('daily-us-today-1','daily-us','Today','What was the best part of your day?',null,null),
('daily-us-today-2','daily-us','Today','What surprised you today?',null,null),
('daily-us-today-3','daily-us','Today','What gave you energy today?',null,null),
('daily-us-today-4','daily-us','Today','What would have made today easier?',null,null),
('daily-us-today-5','daily-us','Today','What are you proud of doing today?',null,null),
('daily-us-today-6','daily-us','Today','What did you notice on your way somewhere?',null,null),
('daily-us-today-7','daily-us','Today','What are you ready to leave behind tonight?',null,null),
('daily-us-today-8','daily-us','Today','What is one thing you learned today?',null,null),
('daily-us-today-9','daily-us','Today','What small kindness did you see?',null,null),
('daily-us-today-10','daily-us','Today','What would you like to remember about today?',null,null),
('daily-us-today-11','daily-us','Today','What are you looking forward to tomorrow?',null,null),
('daily-us-today-12','daily-us','Today','What helped you pause today?',null,null),
('daily-us-today-13','daily-us','Today','What would you like more of this week?',null,null),
('daily-us-today-14','daily-us','Today','What did you make time for yourself today?',null,null),
('daily-us-today-15','daily-us','Today','What is on your mind right now?',null,null),
('daily-us-today-16','daily-us','Today','What felt easier than you expected today?',null,null),
('daily-us-today-17','daily-us','Today','What was something beautiful you saw?',null,null),
('daily-us-today-18','daily-us','Today','What would the title of today be?',null,null),
('daily-us-today-19','daily-us','Today','What are you glad you said yes to?',null,null),
('daily-us-today-20','daily-us','Today','What did you enjoy eating today?',null,null),
('daily-us-appreciation-1','daily-us','Appreciation','What is a quality you appreciate in yourself?',null,null),
('daily-us-appreciation-2','daily-us','Appreciation','Who made your week better?',null,null),
('daily-us-appreciation-3','daily-us','Appreciation','What part of home are you grateful for?',null,null),
('daily-us-appreciation-4','daily-us','Appreciation','What recent conversation stayed with you?',null,null),
('daily-us-appreciation-5','daily-us','Appreciation','What is something you used to wish for that you have now?',null,null),
('daily-us-appreciation-6','daily-us','Appreciation','What simple comfort do you love?',null,null),
('daily-us-appreciation-7','daily-us','Appreciation','What skill are you glad you learned?',null,null),
('daily-us-appreciation-8','daily-us','Appreciation','What is something your body helped you do today?',null,null),
('daily-us-appreciation-9','daily-us','Appreciation','Which friend are you glad is in your life?',null,null),
('daily-us-appreciation-10','daily-us','Appreciation','What is something you like about this season?',null,null),
('daily-us-appreciation-11','daily-us','Appreciation','What do you appreciate about our differences?',null,null),
('daily-us-appreciation-12','daily-us','Appreciation','What family memory makes you smile?',null,null),
('daily-us-appreciation-13','daily-us','Appreciation','What is a place you are glad exists?',null,null),
('daily-us-appreciation-14','daily-us','Appreciation','What do you enjoy about your daily routine?',null,null),
('daily-us-appreciation-15','daily-us','Appreciation','What is a small thing you sometimes take for granted?',null,null),
('daily-us-appreciation-16','daily-us','Appreciation','What opportunity are you thankful for?',null,null),
('daily-us-appreciation-17','daily-us','Appreciation','What is one thing about me you noticed recently?',null,null),
('daily-us-appreciation-18','daily-us','Appreciation','What helped you through a difficult moment?',null,null),
('daily-us-appreciation-19','daily-us','Appreciation','What is a gift you still enjoy?',null,null),
('daily-us-appreciation-20','daily-us','Appreciation','What ordinary sound do you find comforting?',null,null),
('daily-us-possibility-1','daily-us','Possibility','What would you do with a surprise day off?',null,null),
('daily-us-possibility-2','daily-us','Possibility','What is a place you want to explore nearby?',null,null),
('daily-us-possibility-3','daily-us','Possibility','What meal should we try making?',null,null),
('daily-us-possibility-4','daily-us','Possibility','What would you like to learn for fun?',null,null),
('daily-us-possibility-5','daily-us','Possibility','What could we do together for under €10?',null,null),
('daily-us-possibility-6','daily-us','Possibility','What is something you would like to start again?',null,null),
('daily-us-possibility-7','daily-us','Possibility','What would your ideal weekend include?',null,null),
('daily-us-possibility-8','daily-us','Possibility','What would you like to photograph?',null,null),
('daily-us-possibility-9','daily-us','Possibility','What book or film would you like to share?',null,null),
('daily-us-possibility-10','daily-us','Possibility','What would you grow in a garden?',null,null),
('daily-us-possibility-11','daily-us','Possibility','What tiny goal would feel good to complete?',null,null),
('daily-us-possibility-12','daily-us','Possibility','What new route would you like to walk?',null,null),
('daily-us-possibility-13','daily-us','Possibility','What would you like to show me from your world?',null,null),
('daily-us-possibility-14','daily-us','Possibility','What would you collect just for pleasure?',null,null),
('daily-us-possibility-15','daily-us','Possibility','What experience would you choose over a gift?',null,null),
('daily-us-possibility-16','daily-us','Possibility','What would you like to make by hand?',null,null),
('daily-us-possibility-17','daily-us','Possibility','What would you do if the weather were perfect?',null,null),
('daily-us-possibility-18','daily-us','Possibility','What could become our next tradition?',null,null),
('daily-us-possibility-19','daily-us','Possibility','What would you like to celebrate soon?',null,null),
('daily-us-possibility-20','daily-us','Possibility','What is a question you would ask your future self?',null,null),
('daily-us-reflection-1','daily-us','Reflection','What helps you feel grounded?',null,null),
('daily-us-reflection-2','daily-us','Reflection','What do you need a little more of today?',null,null),
('daily-us-reflection-3','daily-us','Reflection','What is something you are getting better at?',null,null),
('daily-us-reflection-4','daily-us','Reflection','What does rest look like for you right now?',null,null),
('daily-us-reflection-5','daily-us','Reflection','What is a thought you want to hold onto?',null,null),
('daily-us-reflection-6','daily-us','Reflection','What have you changed your mind about lately?',null,null),
('daily-us-reflection-7','daily-us','Reflection','What is something you want to approach with patience?',null,null),
('daily-us-reflection-8','daily-us','Reflection','What makes you feel most like yourself?',null,null),
('daily-us-reflection-9','daily-us','Reflection','What is one thing you can simplify?',null,null),
('daily-us-reflection-10','daily-us','Reflection','What have you learned about friendship?',null,null),
('daily-us-reflection-11','daily-us','Reflection','What gives you a sense of belonging?',null,null),
('daily-us-reflection-12','daily-us','Reflection','What is a risk you are glad you took?',null,null),
('daily-us-reflection-13','daily-us','Reflection','What does enough mean to you today?',null,null),
('daily-us-reflection-14','daily-us','Reflection','What are you curious about at the moment?',null,null),
('daily-us-reflection-15','daily-us','Reflection','What makes it easier for you to ask for help?',null,null),
('daily-us-reflection-16','daily-us','Reflection','What would you tell yourself a year ago?',null,null),
('daily-us-reflection-17','daily-us','Reflection','What is something you have made peace with?',null,null),
('daily-us-reflection-18','daily-us','Reflection','What do you want to protect time for?',null,null),
('daily-us-reflection-19','daily-us','Reflection','What kind of day leaves you content?',null,null),
('daily-us-reflection-20','daily-us','Reflection','What would help you feel supported this week?',null,null)
on conflict(id) do update set prompt=excluded.prompt, category=excluded.category, option_a=excluded.option_a, option_b=excluded.option_b;
